force-app/main/default/objects/Deleted_Job__c/Deleted_Job__c.object-meta.xml
<CustomObject>
    <label>Deleted Job</label>
    <nameField>
        <displayFormat>DELJOBS-{0000}/{YYYY}</displayFormat>
        <label>Deleted Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deleted Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deleted_Job__c/fields/JobID__c.field-meta.xml
<CustomField>
    <fullName>JobID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>JobID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mailshot__c/Mailshot__c.object-meta.xml
<CustomObject>
    <label>Mailshot</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>E4O</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/websiteJobsSyncTest.cls
@IsTest
public with sharing class websiteJobsSyncTest {
  private static final String REQUEST_BODY_WITH_CONTENT = '{"dateFrom":"2000-01-01 00:00:00", "closedOnly":"true", "contentOnly":"true", "publishedOnly":"true", "limitNum" : "1"}';
  private static final String REQUEST_BODY_WITHOUT_CONTENT = '{"dateFrom":"2000-01-01 00:00:00", "closedOnly":"true", "contentOnly":"false", "publishedOnly":"true", "limitNum" : "1"}';

  @TestSetup
  private static void setup() {
    TestDataFactory.TestData data = TestDataFactory.generateData();
    data.job.StageName = 'Closed Won';
    data.job.Job_Type__c = 'Content';
    update data.job;
  }

  @IsTest
  static void testJobsSync01() {
    Opportunity job = [SELECT Id FROM Opportunity LIMIT 1];
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.addHeader('httpMethod', 'POST');
    req.requestUri = '/services/apexrest/jobs/sync';
    req.requestBody = Blob.valueof(REQUEST_BODY_WITH_CONTENT);
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    List<Opportunity> resp = websiteJobsSync.getJobs();
    Test.stopTest();
    System.assertEquals(1, resp.size());
    System.assertEquals(resp[0].Id, job.Id);
  }

  @IsTest
  static void testJobsSync02() {
    Opportunity job = [SELECT Job_Type__c FROM Opportunity LIMIT 1];
    job.Job_Type__c = 'Live';
    update job;
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.addHeader('httpMethod', 'POST');
    req.requestUri = '/services/apexrest/jobs/sync';
    req.requestBody = Blob.valueof(REQUEST_BODY_WITHOUT_CONTENT);
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    List<Opportunity> resp = websiteJobsSync.getJobs();
    Test.stopTest();
    System.assertEquals(1, resp.size());
    System.assertEquals(resp[0].Id, job.Id);
  }

  @IsTest
  static void testJobsSyncDelete() {
    Mailshot__c mailshot = [SELECT Id FROM Mailshot__c LIMIT 1];
    delete mailshot;
    Opportunity job = [SELECT Id FROM Opportunity LIMIT 1];
    delete job;
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.addHeader('httpMethod', 'GET');
    req.requestUri = '/services/apexrest/jobs/sync';
    req.requestBody = Blob.valueof(REQUEST_BODY_WITH_CONTENT);
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    List<Deleted_Job__c> resp = websiteJobsSync.getDeletedJobs();
    Test.stopTest();
    System.assertEquals(1, resp.size());
    System.assertEquals(job.Id, resp[0].JobID__c);
  }
}