force-app/main/default/objects/Account/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <label>Freelance</label>
</RecordType>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APL-{000000}-{YYYY}</displayFormat>
        <label>Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appications</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <description>Freelancer Record type</description>
    <label>Freelance Candidate</label>
</RecordType>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IV-{0000}/{MM}-{YYYY}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Freelance Candidate, Permanent Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <businessProcess>Freelance</businessProcess>
    <label>Freelance</label>
</RecordType>

force-app/main/default/classes/OverviewInterviewsControllerTest.cls
@IsTest
public with sharing class OverviewInterviewsControllerTest {
  private static final String CURRENT_WEEK = 'Current Week';

  @TestSetup
  private static void setup() {
    Account acc = new Account(Name = 'Test Account');
    insert acc;
    Opportunity job = new Opportunity(
      LegacyOpaID__c = '123',
      Name = 'Test Job',
      AccountId = acc.Id,
      StageName = 'Qualification',
      CloseDate = Date.today().addDays(30),
      Publish__c = true
    );
    insert job;
    Contact contact = new Contact(
      LastName = 'Test Contact',
      Email = 'test@test.com',
      RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('Freelance')
        .getRecordTypeId()
    );
    insert contact;
    Applicant__c app = new Applicant__c(
      Candidate__c = contact.Id,
      Job__c = job.Id
    );
    insert app;
    insert new List<Interview__c>{
      new Interview__c(
        Applicant__c = app.Id,
        Candidate__c = contact.Id,
        Account__c = acc.Id,
        Job__c = job.Id,
        Start_Date_Time__c = (DateTime) System.today().AddDays(8)
      ),
      new Interview__c(
        Applicant__c = app.Id,
        Candidate__c = contact.Id,
        Account__c = acc.Id,
        Job__c = job.Id,
        Start_Date_Time__c = (DateTime) System.today().AddDays(9)
      ),
      new Interview__c(
        Applicant__c = app.Id,
        Candidate__c = contact.Id,
        Account__c = acc.Id,
        Job__c = job.Id,
        Start_Date_Time__c = (DateTime) System.today().AddDays(10)
      )
    };
  }

  @IsTest
  static void testGetInterviewsMapPositive() {
    Test.startTest();
    Map<Integer, List<Interview__c>> result = OverviewInterviewsController.getInterviewsMap(
      OverviewInterviewsController.NEXT_WEEK
    );
    Test.stopTest();
    System.assertNotEquals(null, result);
    Integer count = 0;
    for (List<Interview__c> interList : result.values()) {
      if (!interList.isEmpty()) {
        count++;
      }
    }
    System.assertEquals(3, count, 'Should be returned three interviews.');
  }

  @IsTest
  static void testGetInterviewsMapNegative() {
    Test.startTest();
    Map<Integer, List<Interview__c>> result = OverviewInterviewsController.getInterviewsMap(
      CURRENT_WEEK
    );
    Test.stopTest();
    System.assertEquals(null, result);
  }
}