force-app/main/default/objects/Account/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <label>Freelance</label>
</RecordType>

force-app/main/default/objects/Candidate_Mailshot__c/Candidate_Mailshot__c.object-meta.xml
<CustomObject>
    <label>Candidate Mailshot</label>
    <nameField>
        <displayFormat>CMS-{000000}-{YYYY}</displayFormat>
        <label>Candidate Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Mailshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Mailshot__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Mailshots</relationshipLabel>
    <relationshipName>Candidate_Mailshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Mailshot__c/fields/Mailshot__c.field-meta.xml
<CustomField>
    <fullName>Mailshot__c</fullName>
    <label>Mailshot</label>
    <referenceTo>Mailshot__c</referenceTo>
    <relationshipLabel>Candidate Mailshots</relationshipLabel>
    <relationshipName>Candidate_Mailshots</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employable__c.field-meta.xml
<CustomField>
    <fullName>Employable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <description>Freelancer Record type</description>
    <label>Freelance Candidate</label>
</RecordType>

force-app/main/default/objects/Mailshot__c/Mailshot__c.object-meta.xml
<CustomObject>
    <label>Mailshot</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailshot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
                <default>true</default>
                <label>Job</label>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Skill_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <masterLabel>Skill Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/candidatesSearchControllerTest.cls
@IsTest
public with sharing class candidatesSearchControllerTest {
  private static final String ACC_NAME = 'candidatesSearchControllerTest Acc candidatesSearchControllerTest';
  private static final String CON_NAME = 'candidatesSearchControllerTest Contact candidatesSearchControllerTest';
  private static final String SKILL_NAME = 'Test Skill';
  private static final String EMAIL = 'testcontact01.candidatesSearchControllerTest@gmail.com';

  @TestSetup
  private static void setup() {
    TestDataFactory.TestData data = TestDataFactory.generateData();
    Account acc01 = new Account(Name = ACC_NAME);
    insert acc01;
    Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
      .get('Freelance Candidate')
      .getRecordTypeId();
    Contact con = new Contact(
      LastName = CON_NAME,
      Email = EMAIL,
      RecordTypeId = conRecordTypeId,
      AccountId = acc01.Id,
      Employable__c = true,
      Is_Manager__c = false,
      Job_Type__c = 'Live',
      Geolocation__latitude__s = 10.022,
      Geolocation__longitude__s = 10.0133
    );
    insert con;
    insert new ContentVersion(
      Title = 'cv',
      PathOnClient = 'cv.docx',
      VersionData = Blob.valueOf('Test Content'),
      IsMajorVersion = true
    );
    List<ContentDocument> documents = [
      SELECT Title, LatestPublishedVersionId
      FROM ContentDocument
    ];
    ContentDocumentLink cdl = new ContentDocumentLink();
    cdl.LinkedEntityId = con.Id;
    cdl.ContentDocumentId = documents[0].Id;
    cdl.ShareType = 'V';
    cdl.Visibility = 'AllUsers';
    insert cdl;
    Skill__c skill01 = new Skill__c(Name = SKILL_NAME);
    insert skill01;
    insert new Skill_Association__c(
      Skill__c = skill01.Id,
      Type__c = 'Primary',
      Level__c = 'Junior',
      isActive__c = true,
      Contact__c = con.Id
    );
  }

  @IsTest
  static void testSearchCandidates() {
    Skill__c skill = [SELECT Id FROM Skill__c LIMIT 1];
    Mailshot__c mailShot = [SELECT Id FROM Mailshot__c LIMIT 1];
    ContentDocument document = [SELECT Id FROM ContentDocument LIMIT 1];
    Test.startTest();
    List<candidatesSearchController.candidateWrapper> result = candidatesSearchController.searchCandidates(
      new List<String>{ skill.Id },
      'Test',
      mailShot.Id,
      'Live',
      10,
      10.022,
      10.0133,
      true
    );
    Test.stopTest();
    System.assertNotEquals(null, result);
    System.assertEquals(1, result.size());
    System.assertEquals(ACC_NAME, result[0].account);
    //System.assertEquals(EMAIL, result[0].email);
    //System.assertEquals(document.Id, result[0].contentDocuments[0]);
    System.assertNotEquals('', result[0].skills);
  }

  @IsTest
  static void testAddCandidateMailshot() {
    Mailshot__c mailShot = [SELECT Id FROM Mailshot__c LIMIT 1];
    Contact con = [SELECT Id FROM Contact LIMIT 1];
    Test.startTest();
    candidatesSearchController.addCandidateMailshot(
      mailShot.Id,
      new List<String>{ con.Id }
    );
    Test.stopTest();
    List<Candidate_Mailshot__c> candidateMail = [
      SELECT Id
      FROM Candidate_Mailshot__c
    ];
    System.assertNotEquals(null, candidateMail);
    System.assertEquals(1, candidateMail.size());
  }
}