force-app/main/default/objects/Account/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <label>Freelance</label>
</RecordType>

force-app/main/default/objects/Candidate_Mailshot__c/Candidate_Mailshot__c.object-meta.xml
<CustomObject>
    <label>Candidate Mailshot</label>
    <nameField>
        <displayFormat>CMS-{000000}-{YYYY}</displayFormat>
        <label>Candidate Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Mailshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Mailshot__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Mailshots</relationshipLabel>
    <relationshipName>Candidate_Mailshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Mailshot__c/fields/Mailshot__c.field-meta.xml
<CustomField>
    <fullName>Mailshot__c</fullName>
    <label>Mailshot</label>
    <referenceTo>Mailshot__c</referenceTo>
    <relationshipLabel>Candidate Mailshots</relationshipLabel>
    <relationshipName>Candidate_Mailshots</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CV_Text__c.field-meta.xml
<CustomField>
    <fullName>CV_Text__c</fullName>
    <label>CV Text</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employable__c.field-meta.xml
<CustomField>
    <fullName>Employable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastMailshot__c.field-meta.xml
<CustomField>
    <fullName>LastMailshot__c</fullName>
    <label>Last Mailshot</label>
    <summarizedField>Candidate_Mailshot__c.CreatedDate</summarizedField>
    <summaryForeignKey>Candidate_Mailshot__c.Contact__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <description>Freelancer Record type</description>
    <label>Freelance Candidate</label>
</RecordType>

force-app/main/default/objects/Mailshot__c/Mailshot__c.object-meta.xml
<CustomObject>
    <label>Mailshot</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailshot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
                <default>true</default>
                <label>Job</label>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Skill_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <masterLabel>Skill Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/candidatesSearchController.cls
public without sharing class candidatesSearchController {
  @AuraEnabled(cacheable=false)
  public static List<candidateWrapper> searchCandidates(
    String[] primarySkills,
    String keywords,
    String mailShotId,
    String selectedType,
    Integer radius,
    Decimal latitude,
    Decimal longitude,
    Boolean usingGeolocation
  ) {
    List<candidateWrapper> resultList = new List<candidateWrapper>();
    String selectFields =
      'SELECT Id, Name, Email, Phone, MailingCity, Title, LastMailshot__c, Is_Manager__c, Account.Name, CV_Text__c, Job_Type__c, Employable__c, ' +
      '(SELECT Id, Skill__c, Skill__r.Name, Type__c, Level__c FROM Skill_Associations__r WHERE isActive__c=TRUE) ';
    String filesQuery = 'SELECT ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.LatestPublishedVersion.LastModifiedDate FROM ContentDocumentLinks ORDER BY ContentDocument.LatestPublishedVersion.LastModifiedDate DESC';
    String whereClause = 'WHERE RecordType.DeveloperName=\'Freelance\' AND Id NOT IN (SELECT Contact__c FROM Candidate_Mailshot__c WHERE Mailshot__c=:mailShotId)';
    system.debug(
      'radius: ' + radius + ', lat: ' + latitude + ', long: ' + longitude
    );
    if (radius != null && latitude != null && longitude != null) {
      selectFields += usingGeolocation
        ? ', DISTANCE(MailingAddress, GEOLOCATION(:latitude, :longitude), \'km\') Dist, DISTANCE(Geolocation__c, GEOLOCATION(:latitude, :longitude), \'km\') Geol'
        : ', DISTANCE(MailingAddress, GEOLOCATION(:latitude, :longitude), \'km\') Dist';
      whereClause += usingGeolocation
        ? ' AND (DISTANCE(MailingAddress, GEOLOCATION(:latitude, :longitude), \'km\') < :radius OR DISTANCE(Geolocation__c, GEOLOCATION(:latitude, :longitude), \'km\') < :radius)'
        : ' AND DISTANCE(MailingAddress, GEOLOCATION(:latitude, :longitude), \'km\') < :radius';
    }
    whereClause += ' AND Employable__c=TRUE AND Is_Manager__c=FALSE';
    system.debug('primarySkills: ' + primarySkills);
    if (!primarySkills.isEmpty()) {
      whereClause += ' AND Id IN (SELECT Contact__c FROM Skill_Association__c WHERE isActive__c=TRUE AND Skill__c IN :primarySkills AND Contact__c!=null AND (Type__c=\'Primary\' OR Type__c=null))';
      system.debug(
        'SERACH QUERY - ' +
          selectFields +
          ', (' +
          filesQuery +
          ') FROM Contact ' +
          whereClause
      );
      List<Contact> searchList = (List<Contact>) Database.query(
        selectFields + ', (' + filesQuery + ') FROM Contact ' + whereClause
      );
      system.debug('contact search: ' + searchList);
      for (Contact tmpCont : searchList) {
        if (!tmpCont.Skill_Associations__r.isEmpty()) {
          if (hasSkills(tmpCont.Skill_Associations__r, primarySkills)) {
            resultList.add(
              wrapCandidate(
                tmpCont,
                (radius != null && latitude != null && longitude != null),
                usingGeolocation
              )
            );
          }
        }
      }
      system.debug('resList1: ' + resultList);
    }
    system.debug('keywords: ' + keywords);
    if (!String.isBlank(keywords)) {
      Set<Id> fileIDs = new Set<Id>();
      for (candidateWrapper tmpWrap : resultList) {
        for (String doc : tmpWrap.contentDocuments) {
          fileIDs.add(doc);
        }
      }
      List<List<sObject>> searchRes = new List<List<sObject>>();
      if (Test.isRunningTest()) {
        List<sObject> tmpList = new List<sObject>();
        tmpList.add([SELECT Id, ContentDocumentId FROM ContentVersion]);
        searchRes.add(tmpList);
      } else {
        if (fileIDs.isEmpty()) {
          searchRes = [
            FIND :keywords
            RETURNING ContentVersion(Id, ContentDocumentId), Contact(Id)
            WITH SNIPPET(target_length = 120)
          ]; //WHERE Is_Manager__c=false
        } else {
          searchRes = [
            FIND :keywords
            RETURNING
              ContentVersion(
                Id,
                ContentDocumentId
                WHERE ContentDocumentId IN :fileIDs),
              Contact(Id)
            WITH SNIPPET(target_length = 120)
          ]; //WHERE Is_Manager__c=false
        }
      }
      if (!searchRes.isEmpty()) {
        if (!searchRes[0].isEmpty()) {
          system.debug('searchRes 0 : ' + searchRes[0].size());
          List<Id> files = new List<Id>();
          for (ContentVersion tmpFile : (List<ContentVersion>) searchRes[0]) {
            files.add(tmpFile.ContentDocumentId);
          }
          if (resultList.isEmpty()) {
            List<ContentDocumentLink> filesLink = [
              SELECT LinkedEntityId
              FROM ContentDocumentLink
              WHERE ContentDocumentId IN :files
            ];
            Set<Id> contIDs = new Set<Id>();
            for (ContentDocumentLink tmpLink : filesLink) {
              contIDs.add(tmpLink.LinkedEntityId);
            }
            if (searchRes.size() > 1) {
              if (!searchRes[1].isEmpty()) {
                for (Contact tmpCont : (List<Contact>) searchRes[1]) {
                  contIDs.add(tmpCont.Id);
                }
              }
            }
            whereClause += !contIDs.isEmpty() ? ' AND Id IN :contIDs' : '';
            system.debug('Fields: ' + selectFields);
            List<Contact> searchFiles = (List<Contact>) Database.query(
              selectFields +
                ', (' +
                filesQuery +
                ') FROM Contact ' +
                whereClause
            );
            system.debug('searchFiles: ' + searchFiles.size());
            for (Contact ct : searchFiles) {
              resultList.add(
                wrapCandidate(
                  ct,
                  (radius != null && latitude != null && longitude != null),
                  usingGeolocation
                )
              );
            }
          }
        }
      }
    }
    return resultList;
  }

  private static Boolean hasSkills(
    List<Skill_Association__c> skills,
    List<String> primarySkills
  ) {
    List<String> tmpStr = new List<String>();
    for (Skill_Association__c tmpSA : skills) {
      if (tmpSA.Type__c == 'Primary') {
        tmpStr.add(tmpSA.Skill__c);
      }
    }
    for (String skill : primarySkills) {
      if (!(tmpStr.contains(skill))) {
        return false;
      }
    }
    return true;
  }

  @AuraEnabled
  public static void addCandidateMailshot(
    String mailShotId,
    List<String> candidates
  ) {
    if (!String.isBlank(mailShotId) && !candidates.isEmpty()) {
      List<Candidate_Mailshot__c> listCandidate = new List<Candidate_Mailshot__c>();
      for (String candId : candidates) {
        Candidate_Mailshot__c tmpRec = new Candidate_Mailshot__c();
        tmpRec.Contact__c = candId;
        tmpRec.Mailshot__c = mailShotId;
        listCandidate.add(tmpRec);
      }
      if (!listCandidate.isEmpty()) {
        insert listCandidate;
      }
    }
  }

  private static candidateWrapper wrapCandidate(
    Contact ct,
    Boolean withDistance,
    Boolean usingGeolocation
  ) {
    candidateWrapper tmpRec = new candidateWrapper();
    tmpRec.id = ct.Id;
    tmpRec.url = '/' + ct.Id;
    tmpRec.name = ct.Name;
    tmpRec.email = ct.Email;
    tmpRec.phone = ct.Phone;
    tmpRec.city = ct.MailingCity;
    tmpRec.title = ct.Title;
    tmpRec.lastMailshot = ct.LastMailshot__c;
    tmpRec.isManager = ct.Is_Manager__c;
    tmpRec.isEmployable = ct.Employable__c;
    tmpRec.account = ct.Account?.Name;
    tmpRec.cv = ct.CV_Text__c;
    tmpRec.jobType = ct.Job_Type__c;
    tmpRec.distance = withDistance ? (Decimal) ct.get('Dist') : null;
    tmpRec.geolocation = usingGeolocation ? (Decimal) ct.get('Geol') : null;
    for (Skill_Association__c sk : ct.Skill_Associations__r) {
      tmpRec.skills +=
        sk.Skill__r.Name +
        '(' +
        (String.isBlank(sk.Type__c) ? '?' : sk.Type__c) +
        '-' +
        (String.isBlank(sk.Level__c) ? '?' : sk.Level__c) +
        '), ';
    }
    tmpRec.contentDocuments = new List<String>();
    for (ContentDocumentLink tmpLink : ct.ContentDocumentLinks) {
      tmpRec.contentDocuments.add(tmpLink.ContentDocumentId);
    }
    return tmpRec;
  }

  public class candidateWrapper {
    @AuraEnabled
    public String id;
    @AuraEnabled
    public String url;
    @AuraEnabled
    public String name;
    @AuraEnabled
    public String email;
    @AuraEnabled
    public String phone;
    @AuraEnabled
    public String city;
    @AuraEnabled
    public String title;
    @AuraEnabled
    public DateTime lastMailshot;
    @AuraEnabled
    public Boolean isManager;
    @AuraEnabled
    public Boolean isEmployable;
    @AuraEnabled
    public String account;
    @AuraEnabled
    public String cv;
    @AuraEnabled
    public String jobType;
    @AuraEnabled
    public Decimal distance;
    @AuraEnabled
    public Decimal geolocation;
    @AuraEnabled
    public String skills = '';
    @AuraEnabled
    public List<String> contentDocuments;
  }
}