force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Account Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZH</fullName>
                <label>Zuid Holland</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>Noord Holland</label>
            </value>
            <value>
                <fullName>UT</fullName>
                <label>Utrecht</label>
            </value>
            <value>
                <fullName>NB</fullName>
                <label>Noord Brabant</label>
            </value>
            <value>
                <fullName>GE</fullName>
                <label>Gelderland</label>
            </value>
            <value>
                <fullName>ZE</fullName>
                <label>Zeeland</label>
            </value>
            <value>
                <fullName>LB</fullName>
                <label>Limboland</label>
            </value>
            <value>
                <fullName>GR</fullName>
                <label>Groningen / Friesland</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Account Team</label>
    <nameField>
        <label>Account Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Teams</relationshipLabel>
    <relationshipName>Account_Teams1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Mailshot__c/Candidate_Mailshot__c.object-meta.xml
<CustomObject>
    <label>Candidate Mailshot</label>
    <nameField>
        <displayFormat>CMS-{000000}-{YYYY}</displayFormat>
        <label>Candidate Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Mailshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Mailshot__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Mailshots</relationshipLabel>
    <relationshipName>Candidate_Mailshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Mailshot__c/fields/Mailshot__c.field-meta.xml
<CustomField>
    <fullName>Mailshot__c</fullName>
    <label>Mailshot</label>
    <referenceTo>Mailshot__c</referenceTo>
    <relationshipLabel>Candidate Mailshots</relationshipLabel>
    <relationshipName>Candidate_Mailshots</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Team__c.field-meta.xml
<CustomField>
    <fullName>Account_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Team</label>
    <referenceTo>Account_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Mailshot__c/Mailshot__c.object-meta.xml
<CustomObject>
    <label>Mailshot</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_List__c/Market_List__c.object-meta.xml
<CustomObject>
    <label>Market List</label>
    <nameField>
        <label>Market List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_List_Account__c/Market_List_Account__c.object-meta.xml
<CustomObject>
    <label>Market List Account</label>
    <nameField>
        <displayFormat>MLA-{000000}/{YYYY}</displayFormat>
        <label>MLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market List Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_List_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market List Accounts</relationshipLabel>
    <relationshipName>Market_List_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_List_Account__c/fields/Market_List__c.field-meta.xml
<CustomField>
    <fullName>Market_List__c</fullName>
    <label>Market List</label>
    <referenceTo>Market_List__c</referenceTo>
    <relationshipLabel>Market List Accounts</relationshipLabel>
    <relationshipName>Market_List_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Market_List__c.field-meta.xml
<CustomField>
    <fullName>Market_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market List</label>
    <referenceTo>Market_List__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/clientSearchController.cls
public without sharing class clientSearchController {
  @AuraEnabled(cacheable=false)
  public static List<accountTeamController.teamWrapper> searchClients(
    String[] skills,
    String mailShotId,
    Integer radius,
    Decimal latitude,
    Decimal longitude,
    String region,
    List<String> markets
  ) {
    List<accountTeamController.teamWrapper> accountsRes = new List<accountTeamController.teamWrapper>();
    if (!skills.isEmpty()) {
      String selectFields = 'SELECT Id, Name, ShippingCity';
      String whereClause = 'WHERE Id IN (SELECT Account__c FROM Skill_Association__c WHERE Skill__c IN :skills AND Account__c!=null)';
      if (!String.isBlank(region)) {
        whereClause += ' AND Account_Region__c = :region';
      }
      if (radius != null && latitude != null && longitude != null) {
        selectFields += ', DISTANCE(ShippingCity, GEOLOCATION(:latitude, :longitude), \'km\') Distance ';
        whereClause += ' AND DISTANCE(ShippingAddress, GEOLOCATION(:latitude, :longitude), \'km\') < :radius';
      }
      if (!markets.isEmpty()) {
        whereClause += ' AND Id IN (SELECT Account__c FROM Market_List_Account__c WHERE Market_List__c IN :markets)';
      }
      List<Account> resAccounts = (List<Account>) Database.query(
        selectFields + ' FROM Account ' + whereClause
      );
      if (!resAccounts.isEmpty()) {
        Set<Id> accountsIDs = new Set<Id>();
        for (Account tmpRec : resAccounts) {
          accountsIDs.add(tmpRec.Id);
        }

        List<Contact> accountConts = [
          SELECT
            Id,
            Name,
            Title,
            Phone,
            Email,
            Account_Team__c,
            Account_Team__r.Name,
            AccountId,
            (SELECT Id, Skill__c, Skill__r.Name FROM Skill_Associations__r)
          FROM Contact
          WHERE
            AccountId IN :accountsIDs
            AND RecordType.DeveloperName = 'Contact'
            AND Id NOT IN (
              SELECT Contact__c
              FROM Candidate_Mailshot__c
              WHERE Mailshot__c = :mailShotId
            )
            AND Email != NULL
          ORDER BY AccountId
        ];
        for (Account tmpAcc : resAccounts) {
          accountTeamController.teamWrapper tmpRec = new accountTeamController.teamWrapper();
          tmpRec.id = tmpAcc.Id;
          tmpRec.name = tmpAcc.Name;
          tmpRec.type = 'account';
          if (radius != null && latitude != null && longitude != null) {
            tmpRec.distance = (Decimal) tmpAcc.get('Distance');
            system.debug('Distance: ' + tmpRec.distance);
          }
          for (Contact tmpCont : accountConts) {
            if (tmpCont.AccountId == tmpAcc.Id) {
              accountTeamController.teamWrapper tmpChild = new accountTeamController.teamWrapper();
              tmpChild.id = tmpCont.Id;
              tmpChild.name = tmpCont.Name;
              tmpChild.title = tmpCont.Title;
              tmpChild.phone = tmpCont.Phone;
              tmpChild.email = tmpCont.Email;
              tmpChild.type = 'contact';
              tmpChild.team = tmpCont.Account_Team__r?.Name;
              if (!tmpCont.Skill_Associations__r.isEmpty()) {
                tmpChild.skills = new List<Skill_Association__c>(
                  tmpCont.Skill_Associations__r
                );
              }
              if (tmpRec.children == null) {
                tmpRec.children = new List<accountTeamController.teamWrapper>{
                  tmpChild
                };
              } else {
                tmpRec.children.add(tmpChild);
              }
            }
          }
          accountsRes.add(tmpRec);
        }
      }
    }
    return accountsRes;
  }

  @AuraEnabled(cacheable=false)
  public static string addClientsToMailshot(
    List<String> contacts,
    String mailshotId
  ) {
    system.debug('Contacts ' + contacts);
    if (
      contacts != null &&
      !contacts.isEmpty() &&
      String.isNotBlank(mailshotId)
    ) {
      List<Candidate_Mailshot__c> mailshotContacts = new List<Candidate_Mailshot__c>();
      for (String tmpRec : contacts) {
        if (String.isNotBlank(tmpRec)) {
          Candidate_Mailshot__c newCont = new Candidate_Mailshot__c();
          newCont.Contact__c = tmpRec;
          newCont.Mailshot__c = mailshotId;
          mailshotContacts.add(newCont);
        }
      }
      if (!mailshotContacts.isEmpty()) {
        insert mailshotContacts;
        return 'Success';
      }
      return 'No clients\' contacts with email address';
    }
    return 'No clients\' contacts provided';
  }
}