force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Account Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZH</fullName>
                <label>Zuid Holland</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>Noord Holland</label>
            </value>
            <value>
                <fullName>UT</fullName>
                <label>Utrecht</label>
            </value>
            <value>
                <fullName>NB</fullName>
                <label>Noord Brabant</label>
            </value>
            <value>
                <fullName>GE</fullName>
                <label>Gelderland</label>
            </value>
            <value>
                <fullName>ZE</fullName>
                <label>Zeeland</label>
            </value>
            <value>
                <fullName>LB</fullName>
                <label>Limboland</label>
            </value>
            <value>
                <fullName>GR</fullName>
                <label>Groningen / Friesland</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Mailshot__c/Mailshot__c.object-meta.xml
<CustomObject>
    <label>Mailshot</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailshot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
                <default>true</default>
                <label>Job</label>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Skill_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <masterLabel>Skill Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/clientSearchControllerTest.cls
@IsTest
public with sharing class clientSearchControllerTest {

    private static final String CON_NAME = 'Test Contact';
    private static final String SKILL_NAME = 'Test Skill';
    private static final String EMAIL = 'testcontact01@gmail.com';
    private static final String ACCOUNT_REGION = 'ZH';

    @TestSetup
	private static void setup() {
        TestDataFactory.TestData data = TestDataFactory.generateData();
        Account acc = data.acc;
        acc.shippinglatitude = 10.022;
        acc.shippinglongitude = 10.0133;
        acc.Account_Region__c = ACCOUNT_REGION;
        update acc;
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con = new Contact(
            LastName = CON_NAME,
            Email = EMAIL,
            RecordTypeId = conRecordTypeId,
            AccountId = data.acc.Id,
            Job_Type__c = 'Live',
            Geolocation__latitude__s = 10.022,
            Geolocation__longitude__s =  10.0133
        );
        insert con;
        insert new ContentVersion (
            Title = 'cv',
            PathOnClient = 'cv.docx',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        List<ContentDocument> documents = [SELECT Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = con.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
        Skill__c skill01 = new Skill__c(Name = SKILL_NAME);
        insert skill01;
        Skill_Association__c skillAccAssot = new Skill_Association__c (
            Skill__c = skill01.Id,
            Type__c = 'Primary',
            Level__c = 'Junior',
            isActive__c = true,
            Account__c = data.acc.Id
        );
        Skill_Association__c skillContactAssot = new Skill_Association__c (
            Skill__c = skill01.Id,
            Type__c = 'Primary',
            Level__c = 'Junior',
            isActive__c = true,
            Contact__c = con.Id
        );
        insert new List<Skill_Association__c>{skillAccAssot, skillContactAssot};
    }   
    
    @IsTest
    static void testSearchClients() {
        Skill__c skill = [SELECT Id FROM Skill__c LIMIT 1];
        Mailshot__c mailShot = [SELECT Id FROM Mailshot__c LIMIT 1]; 
        Account acc = [SELECT Name FROM Account LIMIT 1];
        Contact con = [SELECT Name FROM Contact LIMIT 1];
        Test.startTest();
        List<accountTeamController.teamWrapper> result = clientSearchController.searchClients(
                                                                    new String[]{skill.Id}, mailshot.Id, 10, 10.022, 10.0133, ACCOUNT_REGION, new String[]{});
        Test.stopTest();
        System.assertNotEquals(null, result);                                                                 
        System.assertEquals(1, result.size());                                                                 
        System.assertEquals(acc.Id, result[0].id);                                                                 
        System.assertEquals(acc.Name, result[0].name);                                                                 
        System.assertEquals('account', result[0].type); 
        System.assertNotEquals(null, result[0].children);                                                                 
        System.assertNotEquals(con.Id, result[0].children[0].Id);                                                                 
    }
}