force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Account Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZH</fullName>
                <label>Zuid Holland</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>Noord Holland</label>
            </value>
            <value>
                <fullName>UT</fullName>
                <label>Utrecht</label>
            </value>
            <value>
                <fullName>NB</fullName>
                <label>Noord Brabant</label>
            </value>
            <value>
                <fullName>GE</fullName>
                <label>Gelderland</label>
            </value>
            <value>
                <fullName>ZE</fullName>
                <label>Zeeland</label>
            </value>
            <value>
                <fullName>LB</fullName>
                <label>Limboland</label>
            </value>
            <value>
                <fullName>GR</fullName>
                <label>Groningen / Friesland</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Advertising__c.field-meta.xml
<CustomField>
    <fullName>Advertising__c</fullName>
    <label>Advertising</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Benefits__c.field-meta.xml
<CustomField>
    <fullName>Benefits__c</fullName>
    <label>Benefits</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CAP_Number__c.field-meta.xml
<CustomField>
    <fullName>CAP_Number__c</fullName>
    <displayFormat>CAP{MM}{YYYY}{00}</displayFormat>
    <label>CAP Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Description__c.field-meta.xml
<CustomField>
    <fullName>Client_Description__c</fullName>
    <label>Client Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Duration_Months__c.field-meta.xml
<CustomField>
    <fullName>Contract_Duration_Months__c</fullName>
    <label>Contract Duration Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Desired_Skills__c.field-meta.xml
<CustomField>
    <fullName>Desired_Skills__c</fullName>
    <label>Desired Skills</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>korter dan 2 weken</fullName>
            </value>
            <value>
                <fullName>2 tot 4 weken</fullName>
            </value>
            <value>
                <fullName>1 tot 2 maanden</fullName>
            </value>
            <value>
                <fullName>3 tot 6 maanden</fullName>
            </value>
            <value>
                <fullName>6 tot 12 maanden</fullName>
            </value>
            <value>
                <fullName>Meer dan 12 maanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5 dagen per week</fullName>
            </value>
            <value>
                <fullName>4 dagen per week</fullName>
            </value>
            <value>
                <fullName>3 dagen per week</fullName>
            </value>
            <value>
                <fullName>2 dagen per week</fullName>
            </value>
            <value>
                <fullName>1 dagen per week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Experience</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Job_Rate__c.field-meta.xml
<CustomField>
    <fullName>Job_Rate__c</fullName>
    <label>Job Rate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Job_Rating__c.field-meta.xml
<CustomField>
    <fullName>Job_Rating__c</fullName>
    <formula>TEXT(Job_Rate__c) + TEXT(IF(High_Urgency__c, 1, 0)+IF(Candidate_can_be_Found__c, 1, 0)+IF(Technicaly_Right_Person__c, 1, 0)+IF( Without_CV__c, 1, 0)+IF( Buy_In__c, 1, 0)+IF( Have_Customers__c, 1, 0)+IF( Quick_Decisions__c, 1, 0)+IF( All_Involved__c, 1, 0)+IF( Available_for_Call__c, 1, 0)+IF( Flexibility_Profile__c, 1, 0)+IF( Flexibility_Process__c, 1, 0)+IF( C_Level_Job__c, 1, 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>E4O</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LegacySkillGroupId__c.field-meta.xml
<CustomField>
    <fullName>LegacySkillGroupId__c</fullName>
    <externalId>true</externalId>
    <label>LegacySkillGroupId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Rate__c.field-meta.xml
<CustomField>
    <fullName>Max_Rate__c</fullName>
    <label>Max Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MD_Description__c.field-meta.xml
<CustomField>
    <fullName>MD_Description__c</fullName>
    <description>Description for Meta Data header on the Web Page</description>
    <label>Meta-Data Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Rate__c.field-meta.xml
<CustomField>
    <fullName>Min_Rate__c</fullName>
    <label>Min Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Project_Purpose__c</fullName>
    <label>Project Purpose</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Start__c</fullName>
    <label>Project Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Start_Other__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Other__c</fullName>
    <description>If no exact date, this text in use, ex: ASAP, Next Year</description>
    <label>Project Start Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Radius__c.field-meta.xml
<CustomField>
    <fullName>Radius__c</fullName>
    <label>Radius</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Recruiter_Email__c.field-meta.xml
<CustomField>
    <fullName>Recruiter_Email__c</fullName>
    <label>Recruiter Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required Skills</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Skill_Group__c.field-meta.xml
<CustomField>
    <fullName>Skill_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Group</label>
    <referenceTo>Skill_Group__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <formula>CAP_Number__c+&quot;-&quot;+IF(ISBLANK(Custom_Slug__c), SUBSTITUTE( Name , &quot; &quot;, &quot;_&quot;), Custom_Slug__c)</formula>
    <label>Slug</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Technical_Skills__c.field-meta.xml
<CustomField>
    <fullName>Technical_Skills__c</fullName>
    <label>Technical Skills</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <label>Work Location</label>
    <scale>7</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Group__c/Skill_Group__c.object-meta.xml
<CustomObject>
    <label>Skill Group</label>
    <nameField>
        <label>Skill Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
                <default>true</default>
                <label>Area</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Experience.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Geen voorkeur</fullName>
    </customValue>
    <customValue>
        <fullName>1 tot 3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3 tot 5 years</fullName>
    </customValue>
    <customValue>
        <fullName>Meer dan 5 years</fullName>
    </customValue>
    <masterLabel>Experience</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Skill_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <masterLabel>Skill Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/websiteJobsSync.cls
@RestResource(urlMapping='/jobs/sync/*')
/**
POST REQUEST EXAMPLE:
URL: /services/apexrest/jobs/sync\
BODY:
{
    “dateFrom” : “2020-10-01 00:00:00" (YYYY-MM-DD HH:MM:SS),
    “publishedOnly” : “true” (WHERE Publish= true / false),
    “closedOnly” : “true” (WHERE isClosed= true / false),
    “contentOnly” : “true” (WHERE Job_Type__c = / != ‘Content’)
    "limitNum" : "10",
    "lastId" : "0060900000BQGDOAA5" (WHERE ID>"0060900000BQGDOAA5")
}
*/
global without sharing class websiteJobsSync {
    @HttpPost
    global static List<Opportunity> getJobs() {
        String query = 'SELECT Id, Name, Slug__c, StageName, Job_Type__c, Work_Location__c, Function__c, Desired_Skills__c, Required_Skills__c, Effort__c, Experience__c, Level__c, Technical_Skills__c, Account.Account_Region__c, '+
                            'Max_Rate__c, Min_Rate__c, Description, Publish__c, Advertising__c, Account.BillingCity, Account.BillingState, Radius__c, Account.ShippingCity, Contract_Duration_Months__c, Duration__c, CAP_Number__c, isInternal__c, '+
                            'Project_Purpose__c, Location__c, Project_Start__c, Project_Start_Other__c, Client_Description__c, Benefits__c, Job_Rate__c, Job_Rating__c, RecordType.Name, Skill_Group__c, Skill_Group__r.Name, LegacySkillGroupId__c, '+
                            'Owner.Name, Owner.Email, Recruiter_Email__c, isClosed, LegacyOpaID__c, CreatedDate, MD_Description__c, '+
                            '(SELECT id, Job__c, Type__c, Level__c, Skill__r.Name, Skill__r.LegacySkillId__c, Skill__r.Alias__c, '+
                                'LegacyObjectID__c, LegacyOpaID__c, LegacySkillID__c '+
                                'FROM Skill_Associations__r) '+
                        'FROM Opportunity';
        String requestQuery = RestContext.request!=null ? (RestContext.request.requestBody!=null ? RestContext.request.requestBody.toString() : '') : '';
        if (!String.isBlank(requestQuery)) {
            Map<String, Object> params = (Map<String, Object>)JSON.deserializeUntyped(requestQuery);
            String dateFrom = RestContext.request!=null ? (String)params.get('dateFrom') : '';
            if (!String.isBlank(dateFrom)) {
                try {
                    DateTime modifyFilter = DateTime.valueOf(dateFrom);//(Datetime)JSON.deserialize(dateFrom, DateTime.class);//"2018-10-01T00:00:00Z"
                    system.debug('modifyFilter: '+modifyFilter);
                } catch (Exception e) {
                    system.debug('Error during date pasing: '+e.getMessage());
                }
                query +=' WHERE LastModifiedDate>=:modifyFilter';
            }
            String closedOnly = RestContext.request!=null ? (String)params.get('closedOnly') : null;
            query+= (!String.isBlank(closedOnly)) ? (query.contains('WHERE') ? ' AND isClosed='+closedOnly : ' WHERE isClosed='+closedOnly) : '';
            String contentOnly = RestContext.request!=null ? (String)params.get('contentOnly') : null;
            if (!String.isBlank(contentOnly)) {
                if (contentOnly=='true') {
                    query+= query.contains('WHERE') ? ' AND Job_Type__c=\'Content\'' : ' WHERE Job_Type__c=\'Content\'';
                } else {
                    query+= query.contains('WHERE') ? ' AND Job_Type__c!=\'Content\'' : ' WHERE Job_Type__c!=\'Content\'';
                }
                system.debug('query: '+query);
            }
            String publishedOnly = RestContext.request!=null ? (String)params.get('publishedOnly') : '';
            query+= (!String.isBlank(publishedOnly)) ? (query.contains('WHERE') ? ' AND Publish__c='+publishedOnly : ' WHERE Publish__c='+publishedOnly) : '';
            String lastId = RestContext.request!=null ? (String)params.get('lastId') : '';
            query+= (!String.isBlank(lastId)) ? (query.contains('WHERE') ? ' AND Id>:lastId' : ' WHERE Id>:lastId') : '';
            query+=' ORDER BY Id ASC';
            String limitNum = RestContext.request!=null ? (String)params.get('limitNum') : '';
            query+= !String.isBlank(limitNum) ? ' LIMIT '+Integer.valueOf(limitNum) : '';
        }
        List<Opportunity> tmpList = new List<Opportunity>();
        try {
            tmpList = Database.query(query);
        } catch (Exception e) {
            system.debug('Error during job sync: '+e.getMessage());
        }
        return tmpList;
    }
    /*
        'city' -> Account.ShippingCity
        'slug' -> ...
        'effort' -> Effort__c
        'region' -> Account.Account_Region__c
        'online' -> Publish__c
        'status' -> StageName
        'on_hold' -> ?
        'job_type' -> Job_Type__c (Content, CW, E4O, Live)
        'location' -> Work_Location__c
        'workplace' -> ?
        'operation' -> ?
        'reference' -> ?
        'vacancy_type' -> ?
        'experience_level' -> Experience__c / Level__c
        'contract_duration' -> Contract_Duration_Months__c / Duration__c
        'recruiter' -> ?
        'desired_disciplines' -> Desired_Skills__c
        'skills' -> Skill_Associations__r (Type__c, Level__c, Skill__r.Name, Skill__r.LegacySkillId__c, Skill__r.Alias__c)
        'time_of_commencement' -> ?
        'required_disciplines' -> Required_Skills_Text__c / Technical__c
        'salary_range' -> Min_Rate__c / Max_Rate__c
        'job_function' -> Function__c
        'description' -> Description
    */

    @HttpGet
    global static List<Deleted_Job__c> getDeletedJobs() {
        return [SELECT Id, JobID__c, LegacyId__c, DeletedDate__c, Owner.Name FROM Deleted_Job__c];
    }
}