force-app/main/default/objects/Account/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BTW_Number__c.field-meta.xml
<CustomField>
    <fullName>BTW_Number__c</fullName>
    <label>BTW Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KVK_Nummer__c.field-meta.xml
<CustomField>
    <fullName>KVK_Nummer__c</fullName>
    <label>KVK Nummer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <label>LinkedIn Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Business Qualification</fullName>
            </value>
            <value>
                <fullName>Team Qualification</fullName>
            </value>
            <value>
                <fullName>Hotness</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Freelance Qualified</fullName>
            </value>
            <value>
                <fullName>Perm Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Available_Date__c.field-meta.xml
<CustomField>
    <fullName>Available_Date__c</fullName>
    <label>Available Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_ID__c.field-meta.xml
<CustomField>
    <fullName>Portal_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Portal ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Situation</fullName>
            </value>
            <value>
                <fullName>Closes</fullName>
            </value>
            <value>
                <fullName>IV Process</fullName>
            </value>
            <value>
                <fullName>Tech Skills</fullName>
            </value>
            <value>
                <fullName>Expectations</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Initial Contact</fullName>
            </value>
            <value>
                <fullName>Motivation</fullName>
            </value>
            <value>
                <fullName>Needs</fullName>
            </value>
            <value>
                <fullName>Relocator</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Candidate USP</fullName>
            </value>
            <value>
                <fullName>Counter Offer</fullName>
            </value>
            <value>
                <fullName>Other Opportunities</fullName>
            </value>
            <value>
                <fullName>Business not to approach</fullName>
            </value>
            <value>
                <fullName>Closing on availability</fullName>
            </value>
            <value>
                <fullName>Selling your service</fullName>
            </value>
            <value>
                <fullName>Selling Exclusivity</fullName>
            </value>
            <value>
                <fullName>Identifying Alarmbells</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/PortalRequest__c/PortalRequest__c.object-meta.xml
<CustomObject>
    <label>Portal Request</label>
    <nameField>
        <displayFormat>PR-{0000}/{MM}/{YYYY}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portal Requests</relationshipLabel>
    <relationshipName>Portal_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/AvailableNow__c.field-meta.xml
<CustomField>
    <fullName>AvailableNow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Now</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/BTW_Number__c.field-meta.xml
<CustomField>
    <fullName>BTW_Number__c</fullName>
    <label>BTW Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portal Requests</relationshipLabel>
    <relationshipName>Portal_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Company_City__c.field-meta.xml
<CustomField>
    <fullName>Company_City__c</fullName>
    <label>Company City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <label>Company Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Company_name__c.field-meta.xml
<CustomField>
    <fullName>Company_name__c</fullName>
    <label>Company name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Company_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Postal_Code__c</fullName>
    <label>Company Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Company_Street__c.field-meta.xml
<CustomField>
    <fullName>Company_Street__c</fullName>
    <label>Company Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/HouseNumber__c.field-meta.xml
<CustomField>
    <fullName>HouseNumber__c</fullName>
    <label>House Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <formula
  >IF(ISNULL(Candidate__c) || ISBLANK(Candidate__c), &quot;utility:add&quot;, &quot;utility:edit&quot;)</formula>
    <label>Icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Inzet__c.field-meta.xml
<CustomField>
    <fullName>Inzet__c</fullName>
    <label>Inzet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/KvK_Number__c.field-meta.xml
<CustomField>
    <fullName>KvK_Number__c</fullName>
    <label>KvK Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Portal_ID__c.field-meta.xml
<CustomField>
    <fullName>Portal_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Portal ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Project_Duration__c.field-meta.xml
<CustomField>
    <fullName>Project_Duration__c</fullName>
    <label>Project Duration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Radius__c.field-meta.xml
<CustomField>
    <fullName>Radius__c</fullName>
    <label>Radius</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Start_from__c.field-meta.xml
<CustomField>
    <fullName>Start_from__c</fullName>
    <label>Start from</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Start_until__c.field-meta.xml
<CustomField>
    <fullName>Start_until__c</fullName>
    <label>Start until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/candidateReviewController.cls
public with sharing class candidateReviewController {
  public static List<Database.upsertResult> createReviewRequest(
    List<websitePushCandidates.candidateWrapper> candidates
  ) {
    List<Database.upsertResult> result = new List<Database.upsertResult>();
    if (candidates != null && !candidates.isEmpty()) {
      List<PortalRequest__c> newList = new List<PortalRequest__c>();
      for (websitePushCandidates.candidateWrapper tmpRec : candidates) {
        if (
          String.isNotBlank(tmpRec.portal_id) ||
          tmpRec.candidate_type == 'Website'
        ) {
          PortalRequest__c newRec = new PortalRequest__c();
          newRec.Candidate__c = String.isNotBlank(tmpRec.sf_id)
            ? tmpRec.sf_id
            : null;
          newRec.City__c = tmpRec.city;
          newRec.Country__c = tmpRec.country;
          newRec.Date_of_Birth__c = tmpRec.date_of_birth;
          newRec.DisplayName__c = tmpRec.display_name;
          newRec.FirstName__c = tmpRec.first_name;
          newRec.HouseNumber__c = tmpRec.house_number;
          //newRec.Inzet__c = tmpRec.inzet; ?
          newRec.LastName__c = tmpRec.Last_name;
          newRec.LinkedIn_Profile__c = tmpRec.linkedin_profile;
          newRec.Location__c = tmpRec.location;
          newRec.PhoneNumber__c = tmpRec.phone_number;
          newRec.Portal_ID__c = tmpRec.portal_id;
          newRec.PostalCode__c = tmpRec.postal_code;
          newRec.Radius__c = tmpRec.radius;
          if (tmpRec.skills != null && !tmpRec.skills.isEmpty()) {
            for (websitePushCandidates.skillWrapper tmpSkill : tmpRec.skills) {
              newRec.Skills__c += tmpSkill.sf_id + ',';
            }
          }
          newRec.Start_from__c = tmpRec.start_from_date;
          newRec.Street__c = tmpRec.street;
          newRec.Title__c = (tmpRec.candidate_title != null &&
            !tmpRec.candidate_title.isEmpty())
            ? String.join(tmpRec.candidate_title, ',')
            : null;
          newRec.company_name__c = tmpRec.company_name;
          newRec.Account__c = String.isNotBlank(tmpRec.sf_company_id)
            ? tmpRec.sf_company_id
            : null;
          newRec.kvk_number__c = tmpRec.kvk_number;
          newRec.btw_number__c = tmpRec.btw_number;
          newRec.Company_Street__c =
            tmpRec.company_address +
            ' ' +
            tmpRec.company_house_no;
          newRec.company_city__c = tmpRec.company_city;
          newRec.company_country__c = tmpRec.company_country;
          newRec.company_postal_code__c = tmpRec.company_postal_code;
          newRec.bank_name__c = tmpRec.bank_name;
          newRec.bank_country__c = tmpRec.bank_country;
          newRec.bank_account__c = tmpRec.bank_account_number;
          newRec.description__c = tmpRec.about_description;
          newRec.type__c = tmpRec.candidate_type;
          newList.add(newRec);
        }
      }
      if (!newList.isEmpty()) {
        result = Database.upsert(newList, PortalRequest__c.Portal_ID__c, false);
      }
    }
    return result;
  }

  @AuraEnabled(cacheable=true)
  public static List<PortalRequest__c> getAllRequests() {
    return [
      SELECT Id, Name, Icon__c
      FROM PortalRequest__c
      WHERE Status__c = 'New'
    ];
  }

  @AuraEnabled(cacheable=true)
  public static PortalRequest__c getRequestMergeData(String requestId) {
    return [
      SELECT
        Id,
        Name,
        FirstName__c,
        LastName__c,
        AvailableNow__c,
        Candidate__c,
        City__c,
        Country__c,
        PostalCode__c,
        HouseNumber__c,
        Street__c,
        Date_of_Birth__c,
        DisplayName__c,
        Inzet__c,
        LinkedIn_Profile__c,
        Location__c,
        PhoneNumber__c,
        Portal_ID__c,
        Project_Duration__c,
        Radius__c,
        Start_from__c,
        Start_until__c,
        Title__c,
        Company_name__c,
        Kvk_number__c,
        BTW_Number__c,
        Company_Street__c,
        Company_city__c,
        Company_country__c
        Company_postal_code__c,
        Bank_name__c,
        Bank_country__c,
        Bank_account__c,
        Description__c,
        Type__c,
        Candidate__r.Description,
        Candidate__r.FirstName,
        Candidate__r.LastName,
        Candidate__r.MailingCity,
        Candidate__r.MailingCountry,
        Candidate__r.MailingPostalCode,
        Candidate__r.MailingStreet,
        Candidate__r.Birthdate,
        Candidate__r.LinkedIn_Profile__c,
        Candidate__r.MobilePhone,
        Candidate__r.Available_Date__c,
        Candidate__r.Title,
        Candidate__r.Portal_ID__c,
        Account__r.Name,
        Account__r.KVK_Nummer__c,
        Account__r.BTW_Number__c,
        Account__r.BillingCity,
        Account__r.BillingCountry,
        Account__r.BillingPostalCode,
        Account__r.BillingStreet,
        Account__r.Bank_Name__c,
        Account__r.AccountNumber,
        Account__r.Bank_Country__c,
        Account__r.Description,
        Account__r.Type
      FROM PortalRequest__c
      WHERE ID = :requestId
    ];
  }

  @AuraEnabled
  public static void rejectRequest(String requestId) {
    List<PortalRequest__c> request = [
      SELECT Id, Status__c
      FROM PortalRequest__c
      WHERE Id = :requestId
    ];
    request[0].Status__c = 'Rejected';
    update request;
  }

  @AuraEnabled
  public static void approveRequest(String requestId) {
    PortalRequest__c request = getRequestMergeData(requestId);
    request.Status__c = 'Approved';
    Contact contact = [
      SELECT
        Id,
        Name,
        FirstName,
        LastName,
        Birthdate,
        MobilePhone,
        LinkedIn_Profile__c,
        MailingStreet,
        MailingPostalCode,
        MailingCity,
        MailingCountry,
        Portal_ID__c,
        Available_Date__c,
        Title
      FROM Contact
      WHERE Id = :request.Candidate__c
      LIMIT 1
    ];

    contact.Id = request.Candidate__c;
    contact.FirstName = request.FirstName__c;
    contact.LastName = request.LastName__c;
    contact.Birthdate = request.Date_of_Birth__c;
    contact.MobilePhone = request.PhoneNumber__c;
    contact.LinkedIn_Profile__c = request.LinkedIn_Profile__c;
    contact.MailingStreet = request.Street__c;
    contact.MailingCountry = request.Country__c;
    contact.Portal_ID__c = request.Portal_ID__c;
    contact.Available_Date__c = request.Start_from__c;
    update contact;

    Account account = [
      SELECT
        Name,
        KVK_Nummer__c,
        BTW_Number__c,
        BillingCity,
        BillingCountry,
        BillingPostalCode,
        BillingStreet,
        Bank_Name__c,
        AccountNumber,
        Bank_Country__c,
        Description,
        Type
      FROM Account
      WHERE Id = :request.Account__c
      LIMIT 1
    ];

    account.Name = request.Name;
    account.KVK_Nummer__c = request.KvK_Number__c;
    account.BTW_Number__c = request.BTW_Number__c;
    account.BillingCity = request.Company_city__c;
    account.BillingCountry = request.Company_country__c;
    account.BillingPostalCode = request.Company_postal_code__c;
    account.BillingStreet = request.Company_Street__c;
    account.Bank_Name__c = request.Bank_name__c;
    //account.AccountNumber = 
    account.Bank_Country__c = request.Bank_country__c;
    account.Description = request.Description__c;
    account.Type = request.Type__c;
    
    update account;
  }
}