force-app/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BTW_Number__c.field-meta.xml
<CustomField>
    <fullName>BTW_Number__c</fullName>
    <label>BTW Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KVK_Nummer__c.field-meta.xml
<CustomField>
    <fullName>KVK_Nummer__c</fullName>
    <label>KVK Nummer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <label>LinkedIn Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Business Qualification</fullName>
            </value>
            <value>
                <fullName>Team Qualification</fullName>
            </value>
            <value>
                <fullName>Hotness</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Freelance Qualified</fullName>
            </value>
            <value>
                <fullName>Perm Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <label>Freelance</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employable__c.field-meta.xml
<CustomField>
    <fullName>Employable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Field_Of_Study__c.field-meta.xml
<CustomField>
    <fullName>Field_Of_Study__c</fullName>
    <label>Field Of Study</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Active__c.field-meta.xml
<CustomField>
    <fullName>Portal_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_ID__c.field-meta.xml
<CustomField>
    <fullName>Portal_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Portal ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Situation</fullName>
            </value>
            <value>
                <fullName>Closes</fullName>
            </value>
            <value>
                <fullName>IV Process</fullName>
            </value>
            <value>
                <fullName>Tech Skills</fullName>
            </value>
            <value>
                <fullName>Expectations</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Initial Contact</fullName>
            </value>
            <value>
                <fullName>Motivation</fullName>
            </value>
            <value>
                <fullName>Needs</fullName>
            </value>
            <value>
                <fullName>Relocator</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Candidate USP</fullName>
            </value>
            <value>
                <fullName>Counter Offer</fullName>
            </value>
            <value>
                <fullName>Other Opportunities</fullName>
            </value>
            <value>
                <fullName>Business not to approach</fullName>
            </value>
            <value>
                <fullName>Closing on availability</fullName>
            </value>
            <value>
                <fullName>Selling your service</fullName>
            </value>
            <value>
                <fullName>Selling Exclusivity</fullName>
            </value>
            <value>
                <fullName>Identifying Alarmbells</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Studierichting__c.field-meta.xml
<CustomField>
    <fullName>Studierichting__c</fullName>
    <label>Studierichting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <description>Freelancer Record type</description>
    <label>Freelance Candidate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Permanent.recordType-meta.xml
<RecordType>
    <fullName>Permanent</fullName>
    <active>true</active>
    <description>Permanent Candidate Record Type</description>
    <label>Permanent Candidate</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>CWP-{0000}/{YYY}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billing_period__c.field-meta.xml
<CustomField>
    <fullName>Billing_period__c</fullName>
    <label>Billing period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Candidate)</relationshipLabel>
    <relationshipName>CandidateProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/project_functie__c.field-meta.xml
<CustomField>
    <fullName>project_functie__c</fullName>
    <label>project_functie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/reiskosten__c.field-meta.xml
<CustomField>
    <fullName>reiskosten__c</fullName>
    <defaultValue>false</defaultValue>
    <label>reiskosten</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Going</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/LegacyObjectID__c.field-meta.xml
<CustomField>
    <fullName>LegacyObjectID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyObjectID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/LegacySkillID__c.field-meta.xml
<CustomField>
    <fullName>LegacySkillID__c</fullName>
    <externalId>true</externalId>
    <label>LegacySkillID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Billing_period.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>bi weekly</fullName>
        <default>true</default>
        <label>bi weekly</label>
    </customValue>
    <customValue>
        <fullName>weekly</fullName>
    </customValue>
    <customValue>
        <fullName>monthly</fullName>
    </customValue>
    <masterLabel>Billing period</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Skill_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <masterLabel>Skill Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/websiteCandidateSync.cls
@RestResource(urlMapping='/candidates/sync/*')
/**
POST REQUEST EXAMPLE:
URL: /services/apexrest/candidates/sync/*
BODY:
{
    “dateFrom” : “2020-10-01 00:00:00" (YYYY-MM-DD HH:MM:SS),
    "limitNum" : "10",
    "lastId" : "0060900000BQGDOAA5" (WHERE ID>"0060900000BQGDOAA5")
}
*/

/*
    Name - Name
    KvK - KVK_Nummer__c
    BTW - BTW_Number__c
    Address - BillingAddress

    Bank Name - Bank_Name__c
    Bank Country - NL
    IBAN / Account - AccountNumber
*/

global without sharing class websiteCandidateSync {
  @HttpPost
  global static List<Contact> getCandidates() {
    String query =
      'SELECT Id, FirstName, LastName, Name, Email, Education__c, Studierichting__c, Field_Of_Study__c, Geolocation__Latitude__s, Geolocation__Longitude__s, MailingLatitude, MailingLongitude, ' +
      'Birthdate, HomePhone, Phone, MobilePhone, LinkedIn_Profile__c, Title, Description, MailingCity, MailingStreet, MailingPostalCode, Portal_Active__c, Portal_ID__c, ' +
      'AccountId, Account.Name, Account.KVK_Nummer__c, Account.BTW_Number__c, Account.Bank_Name__c, Account.AccountNumber, Account.LegacyOpaID__c, ' +
      'Account.BillingCity, Account.BillingCountry, Account.BillingPostalCode, Account.BillingState, Account.BillingStreet, ' +
      '(SELECT id, Contact__c, Type__c, Level__c, Skill__r.Name, Skill__r.LegacySkillId__c, Skill__r.Alias__c, ' +
      'LegacyObjectID__c, LegacyOpaID__c, LegacySkillID__c ' +
      'FROM Skill_Associations__r WHERE isActive__c = true) ' +
      'FROM Contact ' +
      'WHERE ((RecordType.DeveloperName=\'Freelance\' OR RecordType.DeveloperName=\'Permanent\') OR (Employable__c=true AND Is_Manager__c=false)) ';
    String requestQuery = RestContext.request != null
      ? (RestContext.request.requestBody != null
          ? RestContext.request.requestBody.toString()
          : '')
      : '';
    if (!String.isBlank(requestQuery)) {
      Map<String, Object> params = (Map<String, Object>) JSON.deserializeUntyped(
        requestQuery
      );
      String dateFrom = RestContext.request != null
        ? (String) params.get('dateFrom')
        : '';
      if (!String.isBlank(dateFrom)) {
        try {
          DateTime modifyFilter = DateTime.valueOf(dateFrom); //(Datetime)JSON.deserialize(dateFrom, DateTime.class);//"2018-10-01T00:00:00Z"
        } catch (Exception e) {
          system.debug('Error during date pasing: ' + e.getMessage());
        }
        query += query.contains('WHERE')
          ? ' AND LastModifiedDate>=:modifyFilter'
          : ' WHERE LastModifiedDate>=:modifyFilter';
      }
      String lastId = RestContext.request != null
        ? (String) params.get('lastId')
        : '';
      query += (!String.isBlank(lastId))
        ? (query.contains('WHERE') ? ' AND Id>:lastId' : ' WHERE Id>:lastId')
        : '';
      query += ' ORDER BY Id ASC';
      String limitNum = RestContext.request != null
        ? (String) params.get('limitNum')
        : '';
      query += !String.isBlank(limitNum)
        ? ' LIMIT ' + Integer.valueOf(limitNum)
        : '';
    }
    List<Contact> tmpList = new List<Contact>();
    try {
      tmpList = Database.query(query);
    } catch (Exception e) {
      system.debug('Error during job sync: ' + e.getMessage());
    }
    return tmpList;
  }

  @HttpGet
  global static Contact getCandidate() {
    RestRequest req = RestContext.request;
    String contactID = req.params.get('candidate_id');
    if (String.isNotBlank(contactID)) {
      List<Contact> contacts = [
        SELECT
          Id,
          FirstName,
          LastName,
          Name,
          Email,
          Education__c,
          Studierichting__c,
          Field_Of_Study__c,
          Geolocation__Latitude__s,
          Geolocation__Longitude__s,
          MailingLatitude,
          MailingLongitude,
          Birthdate,
          HomePhone,
          Phone,
          MobilePhone,
          LinkedIn_Profile__c,
          Title,
          Description,
          MailingCity,
          MailingStreet,
          MailingPostalCode,
          Portal_Active__c,
          Portal_ID__c,
          AccountId,
          Account.Name,
          Account.KVK_Nummer__c,
          Account.BTW_Number__c,
          Account.Bank_Name__c,
          Account.AccountNumber,
          Account.LegacyOpaID__c,
          Account.BillingCity,
          Account.BillingCountry,
          Account.BillingPostalCode,
          Account.BillingState,
          Account.BillingStreet,
          (
            SELECT
              id,
              Name,
              reiskosten__c,
              project_functie__c,
              Account__c,
              Account__r.Name,
              Manager__c,
              Manager__r.Name,
              Manager__r.Email,
              Status__c,
              Billing_period__c
            FROM CandidateProjects__r
            WHERE Status__c != 'Draft'
          ),
          (
            SELECT
              id,
              Contact__c,
              Type__c,
              Level__c,
              Skill__r.Name,
              Skill__r.LegacySkillId__c,
              Skill__r.Alias__c,
              LegacyObjectID__c,
              LegacyOpaID__c,
              LegacySkillID__c
            FROM Skill_Associations__r
            WHERE isActive__c = TRUE
          )
        FROM Contact
        WHERE Id = :contactID
      ];
      return contacts.isEmpty() ? null : contacts[0];
    } else {
      return null;
    }
  }
}