force-app/main/default/objects/Account/fields/IT_Teams__c.field-meta.xml
<CustomField>
    <fullName>IT_Teams__c</fullName>
    <label>IT Teams</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Team__c/Account_Team__c.object-meta.xml
<CustomObject>
    <label>Account Team</label>
    <nameField>
        <label>Account Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Teams</relationshipLabel>
    <relationshipName>Account_Teams1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Team__c.field-meta.xml
<CustomField>
    <fullName>Account_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Team</label>
    <referenceTo>Account_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/accountTeamControllerTest.cls
@isTest
public with sharing class accountTeamControllerTest {

    private static final String ACC_NAME = 'Test Acc';
    private static final String CON_NAME = 'Test Contact';

    @TestSetup
	private static void setup() {
        Account acc01 = new Account(Name = ACC_NAME, IT_Teams__c = 'TI; HR');
        Account acc02 = new Account(Name = ACC_NAME + '02');
        insert new List<Account>{acc01, acc02};
        Account_Team__c accTeam = new Account_Team__c(Name = 'Test Account Team', Account__c = acc02.Id);
        insert accTeam;
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con01 = new Contact(
            LastName = CON_NAME,
            Email = 'testContact01@gmail.com',
            RecordTypeId = conRecordTypeId,
            AccountId = acc02.Id
        );
        Contact con02 = new Contact(
            LastName = CON_NAME + '02',
            Email = 'testContact02@gmail.com',
            RecordTypeId = conRecordTypeId,
            AccountId = acc02.Id,
            Account_Team__c = accTeam.Id
        );
        insert new List<Contact>{con01, con02};
    }

    @IsTest
    static void testAutoCreateTeamsTrigger() {
        Id accId = [SELECT Id FROM Account WHERE Name =: ACC_NAME].Id;
        List<Account_Team__c> accTeamList = [SELECT Id FROM Account_Team__c WHERE Account__c =: accId];
        System.assertEquals(2, accTeamList.size());
    }

    @IsTest
    static void testGetAccountTeam() {
        Id accId = [SELECT Id FROM Account WHERE Name =: ACC_NAME + '02'].Id;
        Test.startTest();
        List<accountTeamController.teamWrapper> teamWrapperList = accountTeamController.getAccountTeam(accId);
        Test.stopTest();
        System.assertNotEquals(0, teamWrapperList.size());
        System.assertEquals(2, teamWrapperList.size());
        Integer countChildren = 0;
        for(accountTeamController.teamWrapper tw: teamWrapperList) {
            if(tw.children != null && !tw.children.isEmpty()) {
                countChildren++;
            }
        }
        System.assertEquals(1, countChildren);
    }

    
    @IsTest
    static void testGetTeams() {
        Id accId = [SELECT Id FROM Account WHERE Name =: ACC_NAME].Id;
        Test.startTest();
        List<Account_Team__c> accTeam = accountTeamController.getTeams(accId);
        Test.stopTest();
        System.assertEquals(2, accTeam.size());
    }

    @IsTest
    static void testLogContactCall() {
        Id accId = [SELECT Id FROM Account WHERE Name =: ACC_NAME].Id;
        Id contactId = [SELECT Id FROM Contact LIMIT 1].Id;
        Test.startTest();
        accountTeamController.logContactCall('subj', 'description', 'callDisposition', contactId, accId);
        Test.stopTest();
        List<Task> taskList = [SELECT Id FROM Task];
        System.assertEquals(1, taskList.size());
    }
    
    @IsTest
    static void testGetContactAccounts() {
        Id contactId = [SELECT Id FROM Contact WHERE Name =: CON_NAME LIMIT 1].Id;
        Test.startTest();
        List<AccountContactRelation> accConRelList = accountTeamController.getContactAccounts(contactId);
        Test.stopTest();
        System.assertEquals(1, accConRelList.size());
    }

}