force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Business Qualification</fullName>
            </value>
            <value>
                <fullName>Team Qualification</fullName>
            </value>
            <value>
                <fullName>Hotness</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Freelance Qualified</fullName>
            </value>
            <value>
                <fullName>Perm Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Situation</fullName>
            </value>
            <value>
                <fullName>Closes</fullName>
            </value>
            <value>
                <fullName>IV Process</fullName>
            </value>
            <value>
                <fullName>Tech Skills</fullName>
            </value>
            <value>
                <fullName>Expectations</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Initial Contact</fullName>
            </value>
            <value>
                <fullName>Motivation</fullName>
            </value>
            <value>
                <fullName>Needs</fullName>
            </value>
            <value>
                <fullName>Relocator</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Candidate USP</fullName>
            </value>
            <value>
                <fullName>Counter Offer</fullName>
            </value>
            <value>
                <fullName>Other Opportunities</fullName>
            </value>
            <value>
                <fullName>Business not to approach</fullName>
            </value>
            <value>
                <fullName>Closing on availability</fullName>
            </value>
            <value>
                <fullName>Selling your service</fullName>
            </value>
            <value>
                <fullName>Selling Exclusivity</fullName>
            </value>
            <value>
                <fullName>Identifying Alarmbells</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Qualification_Answer__c/Qualification_Answer__c.object-meta.xml
<CustomObject>
    <label>Qualification Answer</label>
    <nameField>
        <displayFormat>QA-{0000000}-{YYYY}</displayFormat>
        <label>QA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification_Answer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Qualification_Question__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Qualification Question</label>
    <referenceTo>Qualification_Question__c</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Question__c/Qualification_Question__c.object-meta.xml
<CustomObject>
    <label>Qualification Question</label>
    <nameField>
        <displayFormat>QQN-{00000}</displayFormat>
        <label>Questions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/qualificationControllerTest.cls
@IsTest 
public class qualificationControllerTest {

    private static final String ACC_NAME = 'Test Acc';

    @TestSetup
	private static void setup() {
        Account acc = new Account(
            Name = ACC_NAME,
            RecordTypeId =  Schema.sObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId(),
            Status__c = 'New'
        );
        insert acc;
        Qualification_Question__c ques = new Qualification_Question__c(
            Question__c = 'test',
            Object__c = 'Account'
        );
        insert ques;
        insert new Qualification_Answer__c(
            Qualification_Question__c = ques.Id,
            Account__c = acc.Id,
            Answer__c = 'Test'
        );
        insert new Lead(
            LastName = 'Lead Name',
            Status = 'New'
        );
        insert new Opportunity(
            Name = 'Test Opp',
            StageName = 'New',
            CloseDate = Date.today().addDays(30)
        );
    }

    @IsTest
    public static void testGetQuestions() {
        Account acc = [SELECT RecordType.Name FROM Account WHERE Name =: ACC_NAME LIMIT 1];
        Test.startTest();
        List<Qualification_Question__c> result = qualificationController.getQuestions('Account', acc.Id, '');
        Test.stopTest();
        System.assertEquals(false, result.isEmpty());
        System.assertEquals(1, result.size());
    }

    @IsTest
    public static void testSaveAnswers() {
        Qualification_Answer__c answer = [SELECT Qualification_Question__c, Account__c, Answer__c FROM Qualification_Answer__c LIMIT 1];
        Test.startTest();
        qualificationController.saveAnswers('Account', JSON.serialize(new List<Qualification_Answer__c>{answer}));
        Test.stopTest();
        List<Qualification_Answer__c> result = [SELECT Qualification_Question__c, Account__c, Answer__c FROM Qualification_Answer__c];
        System.assertEquals(false, result.isEmpty());
        System.assertEquals(1, result.size());
        System.assertEquals(answer.Qualification_Question__c, result[0].Qualification_Question__c);
        System.assertEquals(answer.Account__c, result[0].Account__c);
        System.assertEquals(answer.Answer__c, result[0].Answer__c);
    }
    
    @IsTest
    public static void testGetStatuses() {
        Test.startTest();
        List<String> accStatusList = qualificationController.getStatuses('Account');
        List<String> leadStatusList = qualificationController.getStatuses('Lead');
        List<String> oppStatusList = qualificationController.getStatuses('Opportunity');
        List<String> conStatusList = qualificationController.getStatuses('Contact');
        Test.stopTest();
        System.assertEquals(false, accStatusList.isEmpty());
        System.assertEquals(false, leadStatusList.isEmpty());
        System.assertEquals(false, oppStatusList.isEmpty());
        System.assertEquals(false, conStatusList.isEmpty());
    }

    @IsTest
    public static void testGetRecordStatus() {
        Account acc = [SELECT Id FROM Account WHERE Name =: ACC_NAME LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Lead lead = [SELECT Id FROM Lead LIMIT 1];
        Test.startTest();
        String accStatus = qualificationController.getRecordStatus('Account', acc.Id);
        String oppStatus = qualificationController.getRecordStatus('Opportunity', opp.Id);
        String leadStatus = qualificationController.getRecordStatus('Lead', lead.Id);
        Test.stopTest();
        System.assertEquals('New', accStatus);
        System.assertEquals('New', oppStatus);
        System.assertEquals('New', leadStatus);
    }
}