force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Business Qualification</fullName>
            </value>
            <value>
                <fullName>Team Qualification</fullName>
            </value>
            <value>
                <fullName>Hotness</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Freelance Qualified</fullName>
            </value>
            <value>
                <fullName>Perm Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Situation</fullName>
            </value>
            <value>
                <fullName>Closes</fullName>
            </value>
            <value>
                <fullName>IV Process</fullName>
            </value>
            <value>
                <fullName>Tech Skills</fullName>
            </value>
            <value>
                <fullName>Expectations</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Initial Contact</fullName>
            </value>
            <value>
                <fullName>Motivation</fullName>
            </value>
            <value>
                <fullName>Needs</fullName>
            </value>
            <value>
                <fullName>Relocator</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Candidate USP</fullName>
            </value>
            <value>
                <fullName>Counter Offer</fullName>
            </value>
            <value>
                <fullName>Other Opportunities</fullName>
            </value>
            <value>
                <fullName>Business not to approach</fullName>
            </value>
            <value>
                <fullName>Closing on availability</fullName>
            </value>
            <value>
                <fullName>Selling your service</fullName>
            </value>
            <value>
                <fullName>Selling Exclusivity</fullName>
            </value>
            <value>
                <fullName>Identifying Alarmbells</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Qualification_Answer__c/Qualification_Answer__c.object-meta.xml
<CustomObject>
    <label>Qualification Answer</label>
    <nameField>
        <displayFormat>QA-{0000000}-{YYYY}</displayFormat>
        <label>QA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification_Answer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Qualification_Question__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Qualification Question</label>
    <referenceTo>Qualification_Question__c</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Question__c/Qualification_Question__c.object-meta.xml
<CustomObject>
    <label>Qualification Question</label>
    <nameField>
        <displayFormat>QQN-{00000}</displayFormat>
        <label>Questions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification_Question__c/fields/Answer_Options__c.field-meta.xml
<CustomField>
    <fullName>Answer_Options__c</fullName>
    <inlineHelpText>Dropdown values separated with &quot;;&quot;</inlineHelpText>
    <label>Answer Options</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Qualification_Question__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Dropdown</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Multiselect</fullName>
            </value>
            <value>
                <fullName>MinMax Date</fullName>
            </value>
            <value>
                <fullName>MinMax Currency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Qualification_Question__c/fields/isRequired__c.field-meta.xml
<CustomField>
    <fullName>isRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qualification_Question__c/fields/Stage_Value__c.field-meta.xml
<CustomField>
    <fullName>Stage_Value__c</fullName>
    <label>Stage Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qualification_Question__c/fields/Use_in_Summary__c.field-meta.xml
<CustomField>
    <fullName>Use_in_Summary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use in Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/qualificationController.cls
public without sharing class qualificationController {
    @AuraEnabled(cacheable=true)
    public static List<Qualification_Question__c> getQuestions(String objectName, String Id, String recordTypeName) {
        //objectName = String.isNotBlank(objectName) ? (objectName.toLowerCase()=='opportunity' ? 'job' : objectName) : '';
        String objectNameCompare = String.isNotBlank(objectName) ? (objectName.toLowerCase()=='opportunity' ? 'job' : objectName) : '';
        if(String.isBlank(recordTypeName)){
            string query = 'select recordType.Name from '+objectName+' where id=:Id';
            system.debug(query);
            Sobject sobj=Database.query(query);
            recordTypeName = (String) sobj.getSobject('recordType').get('Name');
        }
        if (String.isNotBlank(objectName)) {
            String query = 'SELECT Id, Question__c, Stage_Value__c, Answer_Options__c, Answer_Type__c, Field_Name__c, Use_in_Summary__c, Description__c, isActive__c, isRequired__c, ';
            query +=            '(Select id, Answer__c, CreatedBy.Name, CreatedDate from Qualification_Answers__r WHERE '+objectName+'__c =:Id ORDER BY CreatedDate DESC) ';
            query +=        'FROM Qualification_Question__c WHERE Object__c LIKE \'%'+objectNameCompare+'%\' ';
            query +=        String.isNotBlank(recordTypeName) ? ' AND (Record_Type__c=:recordTypeName OR Record_Type__c=null) ' : '';
            query +=        'ORDER By Order__c';
            system.debug(query);
            return (List<Qualification_Question__c>)Database.query(query);
        } else {
            return null;
        }
    }

    @AuraEnabled(cacheable=false)
    public static void saveAnswers(String objectName, String answers) {
        system.debug(answers);
        if (!String.isBlank(objectName) && !String.isBlank(answers)) {
            List<Qualification_Answer__c> tmpList = (List<Qualification_Answer__c>) JSON.deserialize(answers, List<Qualification_Answer__c>.class);
            if (!tmpList.isEmpty()) {
                upsert tmpList;
            }
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getStatuses(String objectName) {
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult;
        switch on objectName {
            when 'Account' {
                fieldResult = Account.Status__c.getDescribe();
            }
            when 'Lead' {
                fieldResult = Lead.Status.getDescribe();
            }
            when 'Opportunity' {
                fieldResult = Opportunity.StageName.getDescribe();
            }
            when 'Contact' {
                fieldResult = Contact.Status__c.getDescribe();
            }
        }
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}
		return pickListValuesList;
    }

    @AuraEnabled(cacheable=true)
    public static String getRecordStatus(String objectName, String Id) {
        String res='';
        String query = 'SELECT ';
        switch on objectName {
            when 'Account', 'Contact' {
                query+= ' Status__c ';
            }
            when 'Lead' {
                query += ' Status ';
            }
            when 'Opportunity' {
                query += ' StageName ';
            }
        }
        query += 'FROM '+objectName+' WHERE Id=:Id';
        List<sObject> tmp = Database.query(query);
        if (tmp!=null && !tmp.isEmpty()) {
            switch on objectName {
                when 'Account', 'Contact' {
                    res = (String)tmp[0].get('Status__c');
                }
                when 'Lead' {
                    res = (String)tmp[0].get('Status');
                }
                when 'Opportunity' {
                    res = (String)tmp[0].get('StageName');
                }
            }
        }
        return res;
    }
}