force-app/main/default/objects/Client_List__c/Client_List__c.object-meta.xml
<CustomObject>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_List_Association__c/Client_List_Association__c.object-meta.xml
<CustomObject>
    <label>Client List Association</label>
    <nameField>
        <displayFormat>CLS-{000000000}</displayFormat>
        <label>CLS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_List_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client List Associations</relationshipLabel>
    <relationshipName>Client_List_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_List_Association__c/fields/Client_List__c.field-meta.xml
<CustomField>
    <fullName>Client_List__c</fullName>
    <label>Client List</label>
    <referenceTo>Client_List__c</referenceTo>
    <relationshipLabel>Client List Associations</relationshipLabel>
    <relationshipName>Client_List_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountListContainerController.cls
public with sharing class AccountListContainerController {
   
    @AuraEnabled
	public static List<Account> getAccountNames(List<Id> accountIdList) {
        return [
            SELECT  Name 
            FROM    Account 
            WHERE   Id IN :accountIdList
            ORDER BY Name ASC
        ];
    }

    @AuraEnabled
	public static Account getAccountDetail(Id accountId, List<String> accountFieldsList) {
        String accountFieldsStr = String.join(accountFieldsList,',');
        Account acc = new Account();
        String accQuerry = 'SELECT ' + accountFieldsStr + 
                            ' FROM Account' + 
                            ' WHERE Id' +
                            ' =: accountId' +
                            ' ORDER BY Name' +
                            ' ASC';

        try {
            acc = Database.query(accQuerry);
        } catch (Exception ex) {
            System.debug('Error while fetching the Accounts: ' + ex.getMessage());
        }
        return acc;
    }

    @AuraEnabled
	public static List<Client_List__c> getClientLists(Id userId) {
        return [
            SELECT  OwnerId, 
                    Name,
                        (SELECT Account__c
                        FROM Client_List_Associations__r
                        ORDER BY Account__r.Name ASC)
            FROM     Client_List__c 
            WHERE    OwnerId = :userId
            ORDER BY Name ASC
        ];
    }
    
}