force-app/main/default/objects/Contact/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Mailshot__c/Mailshot__c.object-meta.xml
<CustomObject>
    <label>Mailshot</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Mailshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailshot__c/fields/HTML_Body__c.field-meta.xml
<CustomField>
    <fullName>HTML_Body__c</fullName>
    <label>HTML Body</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Mailshot__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Mailshots</relationshipLabel>
    <relationshipName>Mailshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mailshot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
                <default>true</default>
                <label>Job</label>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    @TestVisible
    public static TestData generateData() {
        TestData res = new TestData();
        Account tmpAcc = new Account(Name='Test Acc');
        insert tmpAcc;
        res.acc = tmpAcc;

        Opportunity job = new Opportunity(
            LegacyOpaID__c= '123',
            Name='Test Job',
            StageName = 'Qualification',
            CloseDate = Date.today().addDays(30),
            Publish__c = true
        );
        insert job;
        res.job = job;
        
        Mailshot__c mailshot = new Mailshot__c(Job__c=res.job.id, Title__c=res.job.Name);
        mailshot.Subject__c='test email';
        mailshot.HTML_Body__c = 'Dear {!Contact.Name}. {!Contact.Email} We would like to to check our  . Please check full description on our website';
        mailshot.Type__c = 'Job';
        insert mailshot;
        res.mailshot = mailshot;
        
        Contact contact = new Contact(LastName='Doe', Email='r.mikita@capwell.nl');
        insert contact;
        res.contact = contact;

        return res;
    }

    public class TestData {
        public Opportunity job;
        public Mailshot__c mailshot;
        public Contact contact;
        public Account acc;
    }
}