force-app/main/default/objects/Contact/fields/Raw_Skills__c.field-meta.xml
<CustomField>
    <fullName>Raw_Skills__c</fullName>
    <label>Raw Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <description>Freelancer Record type</description>
    <label>Freelance Candidate</label>
</RecordType>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SkillAssociation_UpdateCandidate_Test.cls
@isTest
public class SkillAssociation_UpdateCandidate_Test {
	@IsTest
    static void testSkillChange() {
        TestDataFactory.TestData data = TestDataFactory.generateData();
        Id freeRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Freelance').getRecordTypeId();
        data.contact.RecordTypeId = freeRecordTypeId;
        update data.contact;

        Contact cn = [SELECT Id, Raw_Skills__c FROM Contact WHERE Id = :data.contact.Id];
        System.assertEquals(null, cn.Raw_Skills__c);
        
        Skill__c sk1 = new Skill__c();
        sk1.Name = 'Product Owner';
        insert sk1;

        Skill__c sk2 = new Skill__c();
        sk2.Name = 'Agile';
        insert sk2;
        
        Skill_Association__c ska = new Skill_Association__c();
        ska.Contact__c = data.contact.Id;
        ska.Skill__c = sk1.Id;
        ska.isActive__c = true;
        insert ska;
        
		ska = new Skill_Association__c();
        ska.Contact__c = data.contact.Id;
        ska.Skill__c = sk2.Id;
        ska.isActive__c = true;
        insert ska;
        
        cn = [SELECT Id, Raw_Skills__c FROM Contact WHERE Id = :data.contact.Id];
        System.assertEquals(true , cn.Raw_Skills__c.containsIgnoreCase('product owner'));
        System.assertEquals(true , cn.Raw_Skills__c.containsIgnoreCase('agile'));
        
        delete ska;
        cn = [SELECT Id, Raw_Skills__c FROM Contact WHERE Id = :data.contact.Id];
        System.assertEquals('Product Owner' , cn.Raw_Skills__c);        
    }
}