force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Situation</fullName>
            </value>
            <value>
                <fullName>Closes</fullName>
            </value>
            <value>
                <fullName>IV Process</fullName>
            </value>
            <value>
                <fullName>Tech Skills</fullName>
            </value>
            <value>
                <fullName>Expectations</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Initial Contact</fullName>
            </value>
            <value>
                <fullName>Motivation</fullName>
            </value>
            <value>
                <fullName>Needs</fullName>
            </value>
            <value>
                <fullName>Relocator</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Candidate USP</fullName>
            </value>
            <value>
                <fullName>Counter Offer</fullName>
            </value>
            <value>
                <fullName>Other Opportunities</fullName>
            </value>
            <value>
                <fullName>Business not to approach</fullName>
            </value>
            <value>
                <fullName>Closing on availability</fullName>
            </value>
            <value>
                <fullName>Selling your service</fullName>
            </value>
            <value>
                <fullName>Selling Exclusivity</fullName>
            </value>
            <value>
                <fullName>Identifying Alarmbells</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/PortalRequest__c/PortalRequest__c.object-meta.xml
<CustomObject>
    <label>Portal Request</label>
    <nameField>
        <displayFormat>PR-{0000}/{MM}/{YYYY}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalRequest__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portal Requests</relationshipLabel>
    <relationshipName>Portal_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortalRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/candidateReviewControllerTest.cls
@isTest
public with sharing class candidateReviewControllerTest {
  @isTest
  static void getAllRequestsTest() {
    PortalRequest__c request = new PortalRequest__c();
    request.Status__c = 'New';
    insert request;

    List<PortalRequest__c> requests = candidateReviewController.getAllRequests();

    System.assertEquals(false, requests.isEmpty());
  }

  @isTest
  static void rejectRequestTest() {
    PortalRequest__c request = new PortalRequest__c();
    insert request;

    candidateReviewController.rejectRequest(request.Id);

    List<PortalRequest__c> requests = [
      SELECT Id, Status__c
      FROM PortalRequest__c
      WHERE Id = :request.Id
    ];

    System.assertEquals('Rejected', requests[0].Status__c);
  }

  @isTest
  static void approveRequestTest() {
    PortalRequest__c request = new PortalRequest__c();
    Contact tempContact = new Contact();
    tempContact.FirstName = 'TestName';
    tempContact.LastName = 'TestLastname';
    insert tempContact;

    request.Candidate__c = tempContact.Id;
    request.FirstName__c = 'reqFirstName';
    request.LastName__c = 'reqLastName';

    insert request;

    candidateReviewController.approveRequest(request.Id);
    List<PortalRequest__c> requests = [
      SELECT Id, Status__c
      FROM PortalRequest__c
      WHERE Id = :request.Id
    ];

    System.assertEquals('Approved', requests[0].Status__c);
  }

  @isTest
  static void createReviewRequestTest() {
    List<websitePushCandidates.skillWrapper> mySkills = new List<websitePushCandidates.skillWrapper>();

    websitePushCandidates.skillWrapper skill = new websitePushCandidates.skillWrapper();
    skill.sf_id = 'testSfId';
    skill.skill_name = 'testSkillName';
    mySkills.add(skill);

    websitePushCandidates.candidateWrapper candidate = new websitePushCandidates.candidateWrapper();
    String[] title = new List<String>();
    title.add('testTitle');
    candidate.candidate_title = title;
    candidate.city = 'TestCity';
    candidate.country = 'Country';
    Date myDate = Date.newInstance(1960, 2, 17);
    candidate.date_of_birth = myDate;
    candidate.display_name = 'Name';
    candidate.first_name = 'FirstName';
    candidate.house_number = 'hNum';
    candidate.inzet = 'inzet';
    candidate.Last_name = 'lastName';
    candidate.linkedin_profile = 'profile';
    candidate.location = 'location';
    candidate.phone_number = 'num';
    candidate.portal_id = 'portalId';
    candidate.postal_code = 'code';
    candidate.radius = 'radius';
    candidate.sf_id = '';
    candidate.skills = mySkills;
    candidate.start_from_date = myDate;
    candidate.street = 'street';
    candidate.user_id = 'userid';

    List<websitePushCandidates.candidateWrapper> candidates = new List<websitePushCandidates.candidateWrapper>{
      candidate
    };

    candidateReviewController.createReviewRequest(candidates);
    String temp = 'FirstName';
    List<PortalRequest__c> req = [
      SELECT Id, Status__c
      FROM PortalRequest__c
      WHERE FirstName__c = :temp
    ];
    System.assertEquals(false, req.IsEmpty());
  }
}