force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Medior</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zoekprofiel doorgeven</fullName>
            </value>
            <value>
                <fullName>Uurtarief opvragen</fullName>
            </value>
            <value>
                <fullName>Beschikbaarheid aanvragen</fullName>
            </value>
            <value>
                <fullName>Freelance opdrachten</fullName>
            </value>
            <value>
                <fullName>Vacatures</fullName>
            </value>
            <value>
                <fullName>Freelance en Vacatures</fullName>
            </value>
            <value>
                <fullName>Terugbelverzoek</fullName>
            </value>
            <value>
                <fullName>Vrijblijvende Offerte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Skill_Group__c.field-meta.xml
<CustomField>
    <fullName>Skill_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Group</label>
    <referenceTo>Skill_Group__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipName>SubSkills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skill_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Group__c/Skill_Group__c.object-meta.xml
<CustomObject>
    <label>Skill Group</label>
    <nameField>
        <label>Skill Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capwell</fullName>
                <default>true</default>
                <label>Capwell</label>
            </value>
            <value>
                <fullName>Experts4Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Group__c/fields/ParentGroup__c.field-meta.xml
<CustomField>
    <fullName>ParentGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Group</label>
    <referenceTo>Skill_Group__c</referenceTo>
    <relationshipLabel>Skill Groups</relationshipLabel>
    <relationshipName>Skill_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Group__c/fields/Plural_Name__c.field-meta.xml
<CustomField>
    <fullName>Plural_Name__c</fullName>
    <label>Plural Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Group__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
                <default>true</default>
                <label>Area</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill_Group_Association__c/Skill_Group_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Group Association</label>
    <nameField>
        <displayFormat>SGA-{00000000}</displayFormat>
        <label>Skill Group Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Group Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group_Association__c/fields/Professional_Skill__c.field-meta.xml
<CustomField>
    <fullName>Professional_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Group Associations</relationshipLabel>
    <relationshipName>Skill_Group_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Group_Association__c/fields/Skill_Group__c.field-meta.xml
<CustomField>
    <fullName>Skill_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Group</label>
    <referenceTo>Skill_Group__c</referenceTo>
    <relationshipLabel>Skill Group Associations</relationshipLabel>
    <relationshipName>Skill_Group_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Skill_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <masterLabel>Skill Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SkillsController.cls
public with sharing class SkillsController {
	@AuraEnabled(Cacheable = true)
	public static Skill__c[] getAllSkills() {
		return [ SELECT Id, Name, Alias__c, Parent__r.Name
							FROM Skill__c
							ORDER BY Name
							LIMIT 50];
	}

	@AuraEnabled(Cacheable = true)
	public static Skill__c[] searchSkills(String searchTerm) {
		// Return all skills when no search term
		searchTerm = searchTerm.trim();

		if (searchTerm == '') {
			return getAllSkills();
		}

		// Prepare query paramters
		searchTerm = '%' + searchTerm + '%';

		return [ SELECT Id, Name, Alias__c, Parent__r.Name
							FROM Skill__c
						WHERE Name LIKE :searchTerm
							 OR Alias__C LIKE :searchTerm
						ORDER BY Name LIMIT 50];
	}

	/*@TestVisible private static List<Skill__c> getAllReferencedAccountSkills(String accountId) {
		List<Skill__c> skills = new List<Skill__c>();
		for (Skill_Account_Association__c assoc : [ SELECT Id, Name, Skill__r.Name, Skill__r.Alias__c
																								FROM Skill_Account_Association__c
																								WHERE Account__r.Id = :accountId
																								ORDER BY Name LIMIT 50]) {
			skills.add(assoc.Skill__r);
		}

		return skills;
	}*/

	/*@TestVisible private static List<Skill__c> getAllReferencedContactSkills(String contactId) {
		List<Skill__c> skills = new List<Skill__c>();
		for (Skill_Contact_Association__c assoc : [ SELECT Id, Name, Skill__r.Name, Skill__r.Alias__c
																								FROM Skill_Contact_Association__c
																								WHERE Contact__r.Id = :contactId
																								ORDER BY Name LIMIT 50]) {
			skills.add(assoc.Skill__r);
		}

		return skills;
	}*/

	/*@TestVisible private static List<Skill__c> getAllReferencedJobSkills(String jobId) {
		List<Skill__c> skills = new List<Skill__c>();

		for (Skill_Job_Association__c assoc : [ SELECT Id, Name, Skill__r.Name, Skill__r.Alias__c
																						FROM Skill_Job_Association__c
																						WHERE Job__r.Id = :jobId
																						ORDER BY Name LIMIT 50]) {
			skills.add(assoc.Skill__r);
		}

		return skills;
	}*/


	/*@AuraEnabled(Cacheable = true)
	public static Skill__c[] getAllReferencedSkills(String recordId, String objectApiName) {
		List<Skill__c> skills = new List<Skill__c>();

		if (objectApiName == 'Account') {
			return getAllReferencedAccountSkills(recordId);
		} else if (objectApiName == 'Contact') {
			return getAllReferencedContactSkills(recordId);
		} else if (objectApiName == 'Opportunity') {
			return getAllReferencedJobSkills(recordId);
		}
		return null;
	}*/

	/*@TestVisible public static void createAccountSkillAssociation(String skillId, String accountId) {
		if ([
				SELECT Id
				FROM Skill_Account_Association__c
				WHERE Skill__c = :skillId
					AND Account__C = :accountId
			].isEmpty()) {
				Skill_Account_Association__c assoc = new Skill_Account_Association__c();
				assoc.Skill__c = skillId;
				assoc.Account__c = accountId;

				insert assoc;
			}
	}*/

	/*@TestVisible public static void createContactSkillAssociation(String skillId, String contactId) {
		if ([SELECT Id FROM Skill_Contact_Association__c WHERE Skill__c = :skillId AND Contact__C = :contactId].isEmpty()) {
				Skill_Contact_Association__c assoc = new Skill_Contact_Association__c();
				assoc.Skill__c = skillId;
				assoc.Contact__c = contactId;
				insert assoc;
			}
	}*/

	/*@TestVisible public static void createJobSkillAssociation(String skillId, String jobId) {
		if ([
				SELECT Id
				FROM Skill_Job_Association__c
				WHERE Skill__c = :skillId
					AND Job__c = :jobId
			].isEmpty()) {
				Skill_Job_Association__c assoc = new Skill_Job_Association__c();
				assoc.Skill__c = skillId;
				assoc.Job__c = jobId;

				insert assoc;
			}
	}*/

	/*@AuraEnabled(Cacheable = false)
	public static void createSkillAssociation(String skillId, String recordId, String objectApiName) {
		try {
			if (objectApiName == 'Account') {
				createAccountSkillAssociation(skillId, recordId);
			} else if (objectApiName == 'Contact') {
				createContactSkillAssociation(skillId, recordId);
			} else if (objectApiName == 'Opportunity') {
				createJobSkillAssociation(skillId, recordId);
			}
		}
		catch(Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}*/

	/*private static void removeAccountSkillAssociation(String skillId, String accountId) {
		DELETE [
			SELECT Id
			FROM Skill_Account_Association__c
			WHERE Skill__c = :skillId
				AND Account__C = :accountId
		];
	}*/

	/*private static void removeContactSkillAssociation(String skillId, String contactId) {
		DELETE [
			SELECT Id
			FROM Skill_Contact_Association__c
			WHERE Skill__c = :skillId
				AND Contact__C = :contactId
		];
	}*/

	/*private static void removeJobSkillAssociation(String skillId, String jobId) {
		DELETE [
			SELECT Id
			FROM Skill_Job_Association__c
			WHERE Skill__c = :skillId
				AND Job__c = :jobId
		];
	}*/

	@AuraEnabled(Cacheable = false)
	public static void removeSkillAssociation(String associationId) {
		Skill_Association__c tmpRec = new Skill_Association__c(Id = associationId);
		delete tmpRec;
	}

	/*@AuraEnabled(Cacheable = false)
	public static void removeSkillAssociation(String skillId, String recordId, String objectApiName) {
		try {
			if (objectApiName == 'Account') {
				removeAccountSkillAssociation(skillId, recordId);
			} else if (objectApiName == 'Contact') {
				removeContactSkillAssociation(skillId, recordId);
			} else if (objectApiName == 'Opportunity') {
				removeJobSkillAssociation(skillId, recordId);
			}
		}
		catch(Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}*/

	@AuraEnabled(cacheable=true)
	public static List<Skill_Association__c> getAssociatedSkills(String objectApiName, String objectId, String skillType) {
		if (objectApiName=='Opportunity') {
			objectApiName = 'Job';
		}
		objectApiName += '__c';
		String query = 'SELECT Id, Skill__r.Name, Skill__c, Type__c, Level__c '+
						'FROM Skill_Association__c '+
						'WHERE isActive__c=true AND '+objectApiName+' = :objectId';
		if (!String.isBlank(skillType)) {
			query += ' AND Type__c = :skillType';
		}
		return (List<Skill_Association__c>)Database.query(query);
	}

	@AuraEnabled
	public static void createSkillAssociation(String objectApiName, String objectId, String skillType, String skillID, String skillLevel){
		if ([SELECT Id FROM Skill_Association__c WHERE Skill__c = :skillId 
				AND (Job__c = :objectId OR Account__c=:objectId OR Contact__c=:objectId)].isEmpty()) {
			Skill_Association__c tmpRec = new Skill_Association__c();
			tmpRec.Skill__c = skillID;
			tmpRec.Type__c = skillType;
			tmpRec.Level__c = skillLevel;
			tmpRec.isActive__c = true;
			switch on objectApiName {
				when 'Contact' {
					tmpRec.Contact__c = objectId;
				}
				when 'Account' {
					tmpRec.Account__c = objectId;
				}
				when 'Opportunity' {
					tmpRec.Job__c = objectId;
				}
				when 'Lead' {
					tmpRec.Lead__c = objectId;
				}
			}
			try {
				insert tmpRec;
			} catch(Exception e) {
				throw new AuraHandledException(e.getMessage());
			}
		}
	}

	@AuraEnabled
	public static void updateSkillLevel(String associationId, String level){
		Skill_Association__c tmpRec = new Skill_Association__c(Id = associationId);
		tmpRec.Level__c = level;
		update tmpRec;
	}

	@AuraEnabled(cacheable=true)
	public static List<Skill_Group__c> getAllGroups(){
		return [SELECT Id, Name, Function__c, (SELECT Professional_Skill__c, Professional_Skill__r.Name FROM Skill_Group_Associations__r) FROM Skill_Group__c WHERE ParentGroup__c = null ORDER BY Name];
	}

	@AuraEnabled(cacheable=true)
	public static List<skillGroups> getAllGroupsTree() {
		List<Skill_Group__c> tmpList = [SELECT Id, Name, Market__c, Function__c, Plural_Name__c, ParentGroup__c FROM Skill_Group__c ORDER BY ParentGroup__c, Name];
		if (tmpList.isEmpty()) {
			return null;
		}
		List<skillGroups> resultList = new List<skillGroups>();
		Map<String, List<skillGroups>> resMap = new Map<String, List<skillGroups>>();
		for (Skill_Group__c tmpRec : tmpList) {
			skillGroups tmpSkill = new skillGroups();
			tmpSkill.id = tmpRec.id;
			tmpSkill.name = tmpRec.Name;
			tmpSkill.market = tmpRec.Market__c;
			tmpSkill.function = tmpRec.Function__c;
			tmpSkill.plural = tmpRec.Plural_Name__c;

			if (tmpRec.ParentGroup__c==null) {
				if (resMap.get('root')==null) {
					resMap.put('root', new List<skillGroups>());
				}
				
				List<skillGroups> tmpItem = resMap.get('root');
				tmpItem.add(tmpSkill);
				resMap.put('root', tmpItem);
			}
		}
		return resultList;
	}

	public class skillGroups {
		@AuraEnabled public String id;
		@AuraEnabled public String name;
		@AuraEnabled public String market;
		@AuraEnabled public String function;
		@AuraEnabled public String plural;
		@AuraEnabled public List<skillGroups> children;
	}
}