force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/opa_candidate_log__c/opa_candidate_log__c.object-meta.xml
<CustomObject>
    <label>opa_candidate_log</label>
    <nameField>
        <label>opa_candidate_log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>opa_candidate_logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/opa_candidate_log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>opa_candidate_logs</relationshipLabel>
    <relationshipName>opa_candidate_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_candidate_log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>opa_candidate_logs</relationshipLabel>
    <relationshipName>opa_candidate_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_candidate_log__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/opa_candidate_log__c/fields/overall_type__c.field-meta.xml
<CustomField>
    <fullName>overall_type__c</fullName>
    <label>overall_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/opa_candidate_log__c/fields/process_type__c.field-meta.xml
<CustomField>
    <fullName>process_type__c</fullName>
    <label>process_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/opa_candidate_log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>opa_candidate_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/opa_recruiter_log__c.object-meta.xml
<CustomObject>
    <label>opa_recruiter_log</label>
    <nameField>
        <label>opa_recruiter_log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>opa_recruiter_logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/opa_recruiter_log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>opa_recruiter_logs</relationshipLabel>
    <relationshipName>opa_recruiter_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>opa_recruiter_logs</relationshipLabel>
    <relationshipName>opa_recruiter_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/fields/ref_type__c.field-meta.xml
<CustomField>
    <fullName>ref_type__c</fullName>
    <label>ref_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/fields/text__c.field-meta.xml
<CustomField>
    <fullName>text__c</fullName>
    <label>text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>opa_recruiter_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/Task_Wrapper__c.object-meta.xml
<CustomObject>
    <label>Task Wrapper</label>
    <nameField>
        <displayFormat>TW-{000000}/{YYYY}</displayFormat>
        <label>Task Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Wrappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Wrapper__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Task Wrappers</relationshipLabel>
    <relationshipName>Task_Wrappers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Task Wrappers</relationshipLabel>
    <relationshipName>Task_Wrappers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Follow_up__c.field-meta.xml
<CustomField>
    <fullName>Follow_up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Follow up?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Follow_up_description__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_description__c</fullName>
    <label>Follow up description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>clBBC</fullName>
            </value>
            <value>
                <fullName>clGGT</fullName>
            </value>
            <value>
                <fullName>clJOBQ</fullName>
            </value>
            <value>
                <fullName>clCAS</fullName>
            </value>
            <value>
                <fullName>clMEET</fullName>
            </value>
            <value>
                <fullName>canQ</fullName>
            </value>
            <value>
                <fullName>canCAS</fullName>
            </value>
            <value>
                <fullName>Obj No recr</fullName>
            </value>
            <value>
                <fullName>Obj PSL</fullName>
            </value>
            <value>
                <fullName>Obj Other</fullName>
            </value>
            <value>
                <fullName>Schedule: date &amp; time</fullName>
            </value>
            <value>
                <fullName>clCheck</fullName>
            </value>
            <value>
                <fullName>canCheck</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
                <default>true</default>
                <label>Sale</label>
            </value>
            <value>
                <fullName>NOsale</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActivityController.cls
public without sharing class ActivityController {
  @AuraEnabled
  public static List<ActivityController.ActivityItem> getActivities(
    String whatOrWhoId
  ) {
    List<ActivityController.ActivityItem> result = new List<ActivityController.ActivityItem>();
    if (String.isBlank(whatOrWhoId)) {
      return result;
    }
    Set<Id> whoOrWhatIds = new Set<Id>{ whatOrWhoId };
    if (whatOrWhoId.startsWith('001')) {
      List<Contact> accConts = [
        SELECT Id
        FROM Contact
        WHERE AccountId = :whatOrWhoId
      ];
      if (accConts != null) {
        for (Contact tmpRec : accConts) {
          whoOrWhatIds.add(tmpRec.Id);
        }
      }
    }
    List<Task> tmpRes = [
      SELECT
        Id,
        ActivityDate,
        CompletedDateTime,
        CallType,
        TaskSubtype,
        Subject,
        Description,
        Status,
        WhatId,
        What.Name,
        WhoId,
        Who.Name,
        OwnerId,
        Owner.Alias
      FROM Task
      WHERE WhoId IN :whoOrWhatIds OR WhatId IN :whoOrWhatIds
      ORDER BY ActivityDate DESC
    ];
    result.addAll(mapActivities(tmpRes));
    if (whatOrWhoId.startsWith('001')) {
      result.addAll(getAccountActivities(whoOrWhatIds));
    } else {
      result.addAll(getContactActivities(whoOrWhatIds));
    }
    return result;
  }

  private static List<ActivityItem> getAccountActivities(Set<Id> accIds) {
    List<opa_recruiter_log__c> legacyLogs = [
      SELECT
        Id,
        Account__c,
        Account__r.Name,
        Contact__c,
        Contact__r.Name,
        overall_type__c,
        process_type__c,
        ref_type__c,
        text__c,
        User__c,
        User__r.Alias,
        CreatedDate__c
      FROM opa_recruiter_log__c
      WHERE Account__c IN :accIds OR Contact__c IN :accIds
      ORDER BY CreatedDate__c DESC
    ];
    return mapLegacyActivities(legacyLogs);
  }

  private static List<ActivityItem> getContactActivities(Set<Id> contIds) {
    List<opa_candidate_log__c> legacyLogs = [
      SELECT
        Id,
        Account__c,
        Account__r.Name,
        Contact__c,
        Contact__r.Name,
        overall_type__c,
        process_type__c,
        ref_type__c,
        text__c,
        User__c,
        User__r.Alias,
        CreatedDate__c
      FROM opa_candidate_log__c
      WHERE Contact__c IN :contIds
      ORDER BY CreatedDate__c DESC
    ];
    return mapLegacyActivities(legacyLogs);
  }

  @AuraEnabled
  public static String recordNewActivity(Task_Wrapper__c newActivity) {
    if (newActivity != null) {
      List<Task> newTasks = new List<Task>{ mapActivityToTask(newActivity) };
      if (newTasks != null && !newTasks.isEmpty()) {
        if (newActivity.Follow_up__c) {
          newTasks.add(createFollowup(newActivity));
        }
        insert newTasks;
        return 'success';
      }
    }
    return 'error';
  }

  private static Task createFollowup(Task_Wrapper__c rec) {
    if (rec != null) {
      Task tmp = new Task();
      tmp.Subject = rec.Type__c + ' - ' + rec.SubType__c;
      tmp.ActivityDate = rec.DueDate__c;
      tmp.Description = rec.Follow_up_description__c;
      tmp.WhatId = rec.Account__c;
      tmp.WhoId = rec.Contact__c;
      tmp.TaskSubtype = 'Call';
      tmp.IsReminderSet = true;
      tmp.Type = 'Call';
      return tmp;
    }
    return null;
  }

  private static Task mapActivityToTask(Task_Wrapper__c rec) {
    if (rec != null) {
      Task tmp = new Task();
      tmp.Subject = rec.Type__c + ' - ' + rec.SubType__c;
      tmp.ActivityDate = Date.today();
      tmp.Description = rec.Description__c;
      tmp.Status = 'Completed';
      tmp.WhatId = rec.Account__c;
      tmp.WhoId = rec.Contact__c;
      tmp.TaskSubtype = 'Call';
      tmp.Type = 'Call';
      return tmp;
    }
    return null;
  }

  private static List<ActivityItem> mapLegacyActivities(
    List<opa_candidate_log__c> logs
  ) {
    List<ActivityItem> result = new List<ActivityItem>();
    if (logs != null) {
      for (opa_candidate_log__c tmpRec : logs) {
        ActivityItem item = new ActivityItem();
        item.activityDate = tmpRec.CreatedDate__c;
        item.activityFormated = item.activityDate != null
          ? item.activityDate.format()
          : 'No Date';
        item.id = tmpRec.Id;
        item.idURL = '/' + tmpRec.Id;
        item.description = tmpRec.text__c;
        item.status = 'Completed';
        item.whoId = tmpRec.Contact__c;
        item.whoURL = String.isNotBlank(tmpRec.Contact__c)
          ? '/' + tmpRec.Contact__c
          : '';
        item.whoName = String.isNotBlank(tmpRec.Contact__r?.Name)
          ? tmpRec.Contact__r?.Name
          : '';
        item.subType = tmpRec.process_type__c;
        item.subject = tmpRec.overall_type__c;
        item.whatId = tmpRec.Account__c;
        item.whatURL = '/' + tmpRec.Account__c;
        item.whatName = tmpRec.Account__r?.Name;
        item.ownerId = tmpRec.User__c;
        item.ownerURL = tmpRec.User__c != null ? '/' + tmpRec.User__c : '';
        item.ownerName = tmpRec.User__c != null ? tmpRec.User__r.Alias : '';
        result.add(item);
      }
    }
    return result;
  }

  private static List<ActivityItem> mapLegacyActivities(
    List<opa_recruiter_log__c> logs
  ) {
    List<ActivityItem> result = new List<ActivityItem>();
    if (logs != null) {
      for (opa_recruiter_log__c tmpRec : logs) {
        ActivityItem item = new ActivityItem();
        item.activityDate = tmpRec.CreatedDate__c;
        item.activityFormated = item.activityDate != null
          ? item.activityDate.format()
          : 'No Date';
        item.id = tmpRec.Id;
        item.idURL = '/' + tmpRec.Id;
        item.description = tmpRec.text__c;
        item.status = 'Completed';
        item.whoId = tmpRec.Contact__c;
        item.whoURL = String.isNotBlank(tmpRec.Contact__c)
          ? '/' + tmpRec.Contact__c
          : '';
        item.whoName = String.isNotBlank(tmpRec.Contact__r?.Name)
          ? tmpRec.Contact__r?.Name
          : '';
        item.subType = tmpRec.process_type__c;
        item.subject = tmpRec.overall_type__c;
        item.whatId = tmpRec.Account__c;
        item.whatURL = '/' + tmpRec.Account__c;
        item.whatName = tmpRec.Account__r?.Name;
        item.ownerId = tmpRec.User__c;
        item.ownerURL = '/' + tmpRec.User__c;
        item.ownerName = tmpRec.User__r?.Alias;
        result.add(item);
      }
    }
    return result;
  }

  private static List<ActivityItem> mapActivities(List<Task> tasks) {
    List<ActivityItem> result = new List<ActivityItem>();
    if (tasks != null) {
      for (Task tmpRec : tasks) {
        ActivityItem item = new ActivityItem();
        item.activityDate = tmpRec.CompletedDateTime != null
          ? tmpRec.CompletedDateTime
          : tmpRec.ActivityDate;
        item.activityFormated = item.activityDate != null
          ? item.activityDate.format()
          : null;
        item.id = tmpRec.Id;
        item.idURL = '/' + tmpRec.Id;
        item.description = tmpRec.Description;
        item.status = tmpRec.Status;
        item.subject = tmpRec.Subject;
        item.subType = tmpRec.TaskSubtype;
        item.type = tmpRec.CallType;
        item.whatId = tmpRec.WhatId;
        item.whatName = tmpRec.What?.Name;
        item.whatURL = '/' + tmpRec.WhatId;
        item.whoId = tmpRec.WhoId;
        item.whoURL = String.isNotBlank(tmpRec.WhoId) ? '/' + tmpRec.WhoId : '';
        item.whoName = String.isNotBlank(tmpRec.WhoId) ? tmpRec.Who?.Name : '';
        item.ownerId = tmpRec.OwnerId;
        item.ownerURL = '/' + tmpRec.OwnerId;
        item.ownerName = tmpRec.Owner?.Alias;
        result.add(item);
      }
    }
    return result;
  }

  public class ActivityItem {
    @AuraEnabled
    public String id { get; set; }
    @AuraEnabled
    public String idURL { get; set; }
    @AuraEnabled
    public DateTime activityDate { get; set; }
    @AuraEnabled
    public String activityFormated { get; set; }
    @AuraEnabled
    public String type { get; set; }
    @AuraEnabled
    public String subType { get; set; }
    @AuraEnabled
    public String subject { get; set; }
    @AuraEnabled
    public String description { get; set; }
    @AuraEnabled
    public String status { get; set; }
    @AuraEnabled
    public String whatId { get; set; }
    @AuraEnabled
    public String whatURL { get; set; }
    @AuraEnabled
    public String whatName { get; set; }
    @AuraEnabled
    public String whoId { get; set; }
    @AuraEnabled
    public String whoURL { get; set; }
    @AuraEnabled
    public String whoName { get; set; }
    @AuraEnabled
    public String ownerId { get; set; }
    @AuraEnabled
    public String ownerURL { get; set; }
    @AuraEnabled
    public String ownerName { get; set; }
  }
}