force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/opa_candidate_log__c/opa_candidate_log__c.object-meta.xml
<CustomObject>
    <label>opa_candidate_log</label>
    <nameField>
        <label>opa_candidate_log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>opa_candidate_logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/opa_candidate_log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>opa_candidate_logs</relationshipLabel>
    <relationshipName>opa_candidate_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_candidate_log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>opa_candidate_logs</relationshipLabel>
    <relationshipName>opa_candidate_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/opa_recruiter_log__c.object-meta.xml
<CustomObject>
    <label>opa_recruiter_log</label>
    <nameField>
        <label>opa_recruiter_log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>opa_recruiter_logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/opa_recruiter_log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>opa_recruiter_logs</relationshipLabel>
    <relationshipName>opa_recruiter_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>opa_recruiter_logs</relationshipLabel>
    <relationshipName>opa_recruiter_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/opa_recruiter_log__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/Task_Wrapper__c.object-meta.xml
<CustomObject>
    <label>Task Wrapper</label>
    <nameField>
        <displayFormat>TW-{000000}/{YYYY}</displayFormat>
        <label>Task Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Wrappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Wrapper__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Task Wrappers</relationshipLabel>
    <relationshipName>Task_Wrappers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Task Wrappers</relationshipLabel>
    <relationshipName>Task_Wrappers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Follow_up__c.field-meta.xml
<CustomField>
    <fullName>Follow_up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Follow up?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Wrapper__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
                <default>true</default>
                <label>Sale</label>
            </value>
            <value>
                <fullName>NOsale</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Notes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActivityControllerTest.cls
@IsTest
public with sharing class ActivityControllerTest {
  @IsTest
  static void runEmptyTest() {
    List<ActivityController.ActivityItem> tmpList = ActivityController.getActivities(
      ''
    );
    System.assertEquals(true, tmpList.isEmpty());
  }

  @IsTest
  static void runTaskTest() {
    Account acc = new Account(Name = 'Test Acc');
    insert acc;

    Contact cnt = new Contact();
    cnt.AccountId = acc.Id;
    cnt.LastName = 'Test Cont';
    insert cnt;

    Task tsk = new Task();
    tsk.Subject = 'call';
    tsk.WhatId = acc.id;
    insert tsk;

    Task cntTsk = new Task();
    tsk.Subject = 'call';
    tsk.WhoId = cnt.id;
    insert cntTsk;

    opa_recruiter_log__c recLog = new opa_recruiter_log__c();
    recLog.Account__c = acc.id;
    insert recLog;

    opa_candidate_log__c cntLog = new opa_candidate_log__c();
    cntLog.Contact__c = cnt.Id;
    insert cntLog;

    List<ActivityController.ActivityItem> tmpList = ActivityController.getActivities(
      acc.id
    );
    System.assertEquals(false, tmpList.isEmpty());
  }

  @isTest
  static void createRecord() {
    Account acc = new Account(Name = 'Test Acc');
    insert acc;

    Contact cnt = new Contact();
    cnt.AccountId = acc.Id;
    cnt.LastName = 'Test Cont';
    insert cnt;

    Task_Wrapper__c tmp = new Task_Wrapper__c();
    tmp.Account__c = acc.Id;
    tmp.COntact__c = cnt.Id;
    tmp.Type__c = 'Call';
    tmp.Follow_up__c = true;
    tmp.DueDate__c = Date.today();

    String result = ActivityController.recordNewActivity(tmp);
    system.assertEquals('success', result);
  }
}