force-app/main/default/objects/Market_List__c/Market_List__c.object-meta.xml
<CustomObject>
    <label>Market List</label>
    <nameField>
        <label>Market List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_List__c/fields/isOnly__c.field-meta.xml
<CustomField>
    <fullName>isOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Market_List_Account__c/Market_List_Account__c.object-meta.xml
<CustomObject>
    <label>Market List Account</label>
    <nameField>
        <displayFormat>MLA-{000000}/{YYYY}</displayFormat>
        <label>MLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market List Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_List_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market List Accounts</relationshipLabel>
    <relationshipName>Market_List_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_List_Account__c/fields/Market_List__c.field-meta.xml
<CustomField>
    <fullName>Market_List__c</fullName>
    <label>Market List</label>
    <referenceTo>Market_List__c</referenceTo>
    <relationshipLabel>Market List Accounts</relationshipLabel>
    <relationshipName>Market_List_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MarketController.cls
public with sharing class MarketController {
    @AuraEnabled(cacheable=true)
    public static List<Market_List__c> getMarkets() {
        return [SELECT Id, Name, Owner.Name, isOnly__c FROM Market_List__c WITH SECURITY_ENFORCED ORDER BY Owner.Name, Name];
    }

    @AuraEnabled(cacheable=true)
    public static List<Market_List_Account__c> getAssociatedMarkets(String accountId) {
        if (!String.isBlank(accountId)) {
            return [SELECT Id, Market_List__c, Market_List__r.Name, Market_List__r.Owner.Name, Market_List__r.isOnly__c 
                        FROM Market_List_Account__c 
                        WHERE Account__c=:accountId WITH SECURITY_ENFORCED];
        } else {
            return null;
        }
    }

    @AuraEnabled(cacheable=false)
    public static void removeAssociation(String id) {
        Market_List_Account__c tmpRec = new Market_List_Account__c(Id=id);
        delete tmpRec;
    }
}