force-app/main/default/objects/Market_List__c/Market_List__c.object-meta.xml
<CustomObject>
    <label>Market List</label>
    <nameField>
        <label>Market List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_List_Account__c/Market_List_Account__c.object-meta.xml
<CustomObject>
    <label>Market List Account</label>
    <nameField>
        <displayFormat>MLA-{000000}/{YYYY}</displayFormat>
        <label>MLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market List Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_List_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market List Accounts</relationshipLabel>
    <relationshipName>Market_List_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_List_Account__c/fields/Market_List__c.field-meta.xml
<CustomField>
    <fullName>Market_List__c</fullName>
    <label>Market List</label>
    <referenceTo>Market_List__c</referenceTo>
    <relationshipLabel>Market List Accounts</relationshipLabel>
    <relationshipName>Market_List_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MarketControllerTest.cls
@IsTest
public class MarketControllerTest {

    private static final String MARKET_LIST_NAME = 'Test Market List';

    @TestSetup
	private static void setup() {
        TestDataFactory.TestData data = TestDataFactory.generateData();
        Market_List__c marketList = new Market_List__c(Name = MARKET_LIST_NAME );
        insert marketList;
        insert new Market_List_Account__c(
            Account__c = data.acc.Id,
            Market_List__c = marketList.Id
        );
    } 
    
    @IsTest
    static void testGetMarkets() {
        Market_List__c marketList = [SELECT Name FROM Market_List__c WHERE Name =: MARKET_LIST_NAME LIMIT 1];
        Test.startTest();
        List<Market_List__c> result = MarketController.getMarkets();
        Test.stopTest();
        System.assertNotEquals(null, result);                                                                 
        System.assertEquals(1, result.size());  
        System.assertEquals(marketList.Name, result[0].Name);  
    }
    
    @IsTest
    static void testGetAssociatedMarkets01() {
        Account acc = [SELECT Name FROM Account LIMIT 1];
        Market_List__c marketList = [SELECT Name FROM Market_List__c WHERE Name =: MARKET_LIST_NAME LIMIT 1];
        Test.startTest();
        List<Market_List_Account__c> result = MarketController.getAssociatedMarkets(acc.Id);
        Test.stopTest();
        System.assertNotEquals(null, result);                                                                 
        System.assertEquals(1, result.size());  
        System.assertEquals(marketList.Id, result[0].Market_List__c);  
    }
    
    @IsTest
    static void testGetAssociatedMarkets02() {
        Test.startTest();
        List<Market_List_Account__c> result = MarketController.getAssociatedMarkets(null);
        Test.stopTest();
        System.assertEquals(null, result);        
    }      

    @IsTest
    static void testRemoveAssociation() {
        Market_List_Account__c marketListAcc = [SELECT Id FROM Market_List_Account__c LIMIT 1];
        Test.startTest();
        MarketController.removeAssociation(marketListAcc.Id);
        Test.stopTest();
        List<Market_List_Account__c> result = [SELECT Id FROM Market_List_Account__c];
        System.assertEquals(0, result.size());  
    }                                                   
    
}