force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UniversalContactTileController.cls
public with sharing class UniversalContactTileController {

    @AuraEnabled(Cacheable=true)
	public static Contact getContactDetail(Id contactId, List<String> conFieldsList) {
        String conFieldsStr = String.join(conFieldsList,',');
        List<Contact> getCon = new List<Contact>();
        String accQuerry = 'SELECT ' + conFieldsStr + 
                            ',(SELECT Skill__r.Name FROM Skill_Associations__r)' +
                            ' FROM Contact' + 
                            ' WHERE Id' +
                            ' =: contactId' +
                            ' ORDER BY Name' +
                            ' ASC';
        try {
            getCon = Database.query(accQuerry);
        } catch (Exception ex) {
            System.debug('Error while fetching the Accounts: ' + ex.getMessage());
        }
        return getCon[0];
    }
}