force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UniversalContactTileControllerTest.cls
@IsTest
public class UniversalContactTileControllerTest {
    
    @TestSetup
	private static void setup() {
        Account acc01 = new Account(Name = 'Test Account 01');
        insert acc01;
        Contact con01 = new Contact(
            LastName = 'Test Contact Name',
            Title = 'Lead',
            AccountId = acc01.Id
        );
        insert con01;
        Skill__c skill = new Skill__c (Name = 'Skill');
        insert skill;
        insert new Skill_Association__c(
            Contact__c = con01.Id,
            Account__c = acc01.Id
        );
    }

    @IsTest
    static void testGetContactDetail() {
        Schema.DescribeSObjectResult r = Contact.sObjectType.getDescribe();
        List<String> fieldsApiNames =  new List<String>();
        for(String apiName : r.fields.getMap().keySet()){
            fieldsApiNames.add(apiName);
        }
        Id conId = [SELECT Id FROM Contact LIMIT 1].Id;
        Test.startTest();
        Contact result = UniversalContactTileController.getContactDetail(conId, fieldsApiNames);
        Test.stopTest();
        System.assertNotEquals(null, result);
        System.assertEquals(conId, result.Id);
        System.assertEquals(1, result.Skill_Associations__r.size());
    }

    
    @IsTest
    static void testGetContactDetailNegative() {
        Id conId = [SELECT Id FROM Contact LIMIT 1].Id;
        try {
        Test.startTest();
        Contact result = UniversalContactTileController.getContactDetail(conId, new List<String>());
        Test.stopTest();
        } catch (Exception e) {
            System.assertEquals('System.ListException', e.getTypeName());
        }
    }
}