force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Qualification_Answer__c/Qualification_Answer__c.object-meta.xml
<CustomObject>
    <label>Qualification Answer</label>
    <nameField>
        <displayFormat>QA-{0000000}-{YYYY}</displayFormat>
        <label>QA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification_Answer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Answer__c/fields/Qualification_Question__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Qualification Question</label>
    <referenceTo>Qualification_Question__c</referenceTo>
    <relationshipLabel>Qualification Answers</relationshipLabel>
    <relationshipName>Qualification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qualification_Question__c/Qualification_Question__c.object-meta.xml
<CustomObject>
    <label>Qualification Question</label>
    <nameField>
        <displayFormat>QQN-{00000}</displayFormat>
        <label>Questions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/Skill_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Association</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Association Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Association__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Associations</relationshipLabel>
    <relationshipName>Skill_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/lead_onConvertTest.cls
@IsTest
public class lead_onConvertTest {

    private static final String ACC_NAME = 'Test Acc';
    private static final String CON_NAME = 'Test Con';

    @TestSetup
	private static void setup() {
        Account acc = new Account(Name = ACC_NAME);
        insert acc;
        Lead lead = new Lead ( 
            FirstName = 'Test',
            LastName = 'Sample',
            Company = 'Testing Sample Co' 
        ); 
        insert lead;  
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con01 = new Contact(
            LastName = CON_NAME,
            Email = 'testContact01@gmail.com',
            RecordTypeId = conRecordTypeId,
            AccountId = acc.Id
        );
        insert con01;
        Qualification_Question__c qq = new Qualification_Question__c ();
        qq.Question__c = 'test Q';
        qq.Object__c = 'ACCOUNT; CONTACT';
        insert qq;
        Qualification_Answer__c qa = new Qualification_Answer__c ();
        qa.Lead__c = lead.Id;
        qa.Answer__c = 'Test';
        qa.Qualification_Question__c = qq.Id;
        insert qa;
        Skill__c s = new Skill__c();
        s.Name = 'Test Skill';
        insert s;
        Skill_Association__c sa = new Skill_Association__c();
        sa.Lead__c = lead.Id;
        sa.Skill__c = s.Id;
        insert sa;
    }
    
    @IsTest
    static void testLeadConvert() {
        Lead lead = [SELECT Id FROM Lead LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Test.startTest();
        Database.LeadConvert lc = new Database.LeadConvert();  
        lc.setLeadId(lead.Id);  
        lc.setConvertedStatus('Qualified'); 
        lc.setAccountId(acc.Id); 
        lc.setContactId(con.Id); 
        Database.LeadConvertResult lcr = Database.convertLead(lc, true);  
        Test.stopTest();
        Skill_Association__c skill = [SELECT Account__c, Contact__c FROM Skill_Association__c LIMIT 1];
        Qualification_Answer__c answer = [SELECT Account__c, Contact__c FROM Qualification_Answer__c LIMIT 1];
        System.assertEquals(acc.Id, skill.Account__c);
        System.assertEquals(con.Id, skill.Contact__c);
        System.assertEquals(acc.Id, answer.Account__c);
        System.assertEquals(con.Id, answer.Contact__c);
    }
}