force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ResumeControllerTest.cls
@IsTest
public with sharing class ResumeControllerTest {
    @IsTest
     static void testFindByContactId() {
        Contact contact = new Contact(LastName='Doe');
        insert contact;
        Resume__c resume = new Resume__c(Contact__c=contact.Id, Text__c='lorem ipsum');
        insert resume;
        Test.startTest();
        Resume__c record = ResumeController.findByContactId(contact.Id);
        Test.stopTest();
        System.assertEquals(resume.Contact__c, record.Contact__c);
    }
}