force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/LegacySkillId__c.field-meta.xml
<CustomField>
    <fullName>LegacySkillId__c</fullName>
    <externalId>true</externalId>
    <label>LegacySkillId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Skill_Group__c/Skill_Group__c.object-meta.xml
<CustomObject>
    <label>Skill Group</label>
    <nameField>
        <label>Skill Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group__c/fields/opaId__c.field-meta.xml
<CustomField>
    <fullName>opaId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>opaId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Skill_Group__c/fields/Parent_OpaId__c.field-meta.xml
<CustomField>
    <fullName>Parent_OpaId__c</fullName>
    <externalId>true</externalId>
    <label>Parent OpaId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Group__c/fields/ParentGroup__c.field-meta.xml
<CustomField>
    <fullName>ParentGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Group</label>
    <referenceTo>Skill_Group__c</referenceTo>
    <relationshipLabel>Skill Groups</relationshipLabel>
    <relationshipName>Skill_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Group__c/fields/Plural_Name__c.field-meta.xml
<CustomField>
    <fullName>Plural_Name__c</fullName>
    <label>Plural Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Group__c/fields/ShowOnRadar__c.field-meta.xml
<CustomField>
    <fullName>ShowOnRadar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show On Radar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Skill_Group_Association__c/Skill_Group_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Group Association</label>
    <nameField>
        <displayFormat>SGA-{00000000}</displayFormat>
        <label>Skill Group Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Group Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group_Association__c/fields/Professional_Skill__c.field-meta.xml
<CustomField>
    <fullName>Professional_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Group Associations</relationshipLabel>
    <relationshipName>Skill_Group_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Group_Association__c/fields/Skill_Group__c.field-meta.xml
<CustomField>
    <fullName>Skill_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Group</label>
    <referenceTo>Skill_Group__c</referenceTo>
    <relationshipLabel>Skill Group Associations</relationshipLabel>
    <relationshipName>Skill_Group_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/websiteSkillGroups.cls
@RestResource(urlMapping='/skill/groups')
global with sharing class websiteSkillGroups {
    @HttpGet
    global static List<groupWrapper> getGroups() {
        List<groupWrapper> resList = new List<groupWrapper>();
        /* for (Skill_Group__c tmpRec : [SELECT Id, opaId__c, Name, Plural_Name__c, Function__c, ParentGroup__c, Parent_OpaId__c, ShowOnRadar__c, (SELECT Name, Professional_Skill__r.Id, Professional_Skill__r.Name, Professional_Skill__r.LegacySkillId__c FROM Skill_Group_Associations__r) FROM Skill_Group__c]) {
            groupWrapper tmpItem = new groupWrapper();
            tmpItem.id = tmpRec.Id;
            tmpItem.opaid = tmpRec.opaId__c;
            tmpItem.name = tmpRec.Name;
            tmpItem.pluralName = tmpRec.Plural_Name__c;
            tmpItem.function = tmpRec.Function__c;
            tmpItem.parentId = tmpRec.ParentGroup__c;
            tmpItem.parentOpaId = tmpRec.Parent_OpaId__c;
            tmpItem.showOnRadar = tmpRec.ShowOnRadar__c; 
            if (!tmpRec.Skill_Group_Associations__r.isEmpty()) {
                tmpItem.skills = new List<skillWrapper>();
                for (Skill_Group_Association__c tmpSkill : tmpRec.Skill_Group_Associations__r) {
                    skillWrapper tmpSkillInner = new skillWrapper();
                    tmpSkillInner.id=tmpSkill.Professional_Skill__r.Id;
                    tmpSkillInner.name=tmpSkill.Professional_Skill__r.Name;
                    tmpSkillInner.opaid=tmpSkill.Professional_Skill__r.LegacySkillId__c;
                    tmpItem.skills.add(tmpSkillInner);
                }
            }
            resList.add(tmpItem);
        } */
        return resList;
    }

    @HttpPost
    global static List<groupWrapper> pushGroups(List<groupWrapper> inbound) {
        return inbound;
    }

    global class groupWrapper{
        global String id;
        global String opaid;
        global String name;
        global String pluralName;
        global String function;
        global String parentId;
        global String parentOpaId;
        global List<skillWrapper> skills;
        global Boolean showOnRadar;
    }

    global class skillWrapper {
        global String id;
        global String opaid;
        global String name;
    }
}