force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Professional Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group__c/Skill_Group__c.object-meta.xml
<CustomObject>
    <label>Skill Group</label>
    <nameField>
        <label>Skill Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group__c/fields/Plural_Name__c.field-meta.xml
<CustomField>
    <fullName>Plural_Name__c</fullName>
    <label>Plural Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Group_Association__c/Skill_Group_Association__c.object-meta.xml
<CustomObject>
    <label>Skill Group Association</label>
    <nameField>
        <displayFormat>SGA-{00000000}</displayFormat>
        <label>Skill Group Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Group Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Group_Association__c/fields/Professional_Skill__c.field-meta.xml
<CustomField>
    <fullName>Professional_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Skill Group Associations</relationshipLabel>
    <relationshipName>Skill_Group_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill_Group_Association__c/fields/Skill_Group__c.field-meta.xml
<CustomField>
    <fullName>Skill_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Group</label>
    <referenceTo>Skill_Group__c</referenceTo>
    <relationshipLabel>Skill Group Associations</relationshipLabel>
    <relationshipName>Skill_Group_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/websiteSkillGroupsTest.cls
@IsTest
private with sharing class websiteSkillGroupsTest {

    private static final String SKILL_NAME = 'Test Skill';

    @TestSetup
	private static void setup() {
        Skill__c skill01 = new Skill__c(Name = SKILL_NAME);
        insert skill01;
        Skill_Group__c skillGroup = new Skill_Group__c(
            Name = 'Test Group 1',
            Plural_Name__c = 'Test Group',
            Function__c = 'Test function'
            );
        insert skillGroup;
        Skill_Group_Association__c skillGroupAssot = new Skill_Group_Association__c();
        skillGroupAssot.Professional_Skill__c = skill01.id;
        skillGroupAssot.Skill_Group__c = skillGroup.Id;
        insert skillGroupAssot;
    }

    @IsTest 
    static void testGetGroups() {
        Skill_Group__c skillGroup = [SELECT Name, Plural_Name__c, Function__c FROM Skill_Group__c LIMIT 1];
        Test.startTest();
            List<websiteSkillGroups.groupWrapper> groupWrapperList = websiteSkillGroups.getGroups();
        Test.stopTest();
        /*System.assertNotEquals(null, groupWrapperList);
        System.assertEquals(1, groupWrapperList.size());
        System.assertEquals(skillGroup.Id, groupWrapperList[0].id);
        System.assertEquals(skillGroup.Name, groupWrapperList[0].name);
        System.assertEquals(skillGroup.Plural_Name__c, groupWrapperList[0].pluralName);
        System.assertEquals(skillGroup.Function__c, groupWrapperList[0].function);
        System.assertNotEquals(null, groupWrapperList[0].skills);
        System.assertEquals(1, groupWrapperList[0].skills.size());*/
    }

    @IsTest 
    static void testPushGroups() {
        Test.startTest();
        List<websiteSkillGroups.groupWrapper> groupWrapperList = new List<websiteSkillGroups.groupWrapper>();
        List<websiteSkillGroups.groupWrapper> result = websiteSkillGroups.pushGroups(groupWrapperList);
        Test.stopTest();
        /*System.assert(result != null);
        System.assert(result.isEmpty());*/
    }
}