force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APL-{000000}-{YYYY}</displayFormat>
        <label>Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appications</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/homeComponentsControllerTest.cls
@IsTest
public class homeComponentsControllerTest {

    @TestSetup
	private static void setup() {
        insert new Lead(LastName = 'Test Lead');
        Opportunity opp =  new Opportunity(
            LegacyOpaID__c= '123',
            Name='Test Job',
            StageName = 'Qualification',
            CloseDate = Date.today().addDays(30),
            Publish__c = true
        );
        insert opp;
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con = new Contact(
            LastName = 'Contact Name',
            Email = 'testcontact01@gmail.com',
            RecordTypeId = conRecordTypeId
        );
        insert con;
        insert new Applicant__c(
            Candidate__c = con.Id,
            Job__c = opp.Id
        );
    } 

    @IsTest
    static void testGetLeads() {
        Test.startTest();
        List<Lead> leadList = homeComponentsController.getLeads();
        Test.stopTest();
        System.assertNotEquals(null, leadList);                                                                 
        System.assertEquals(1, leadList.size());        
    }

    @IsTest
    static void testGetJobs() {
        Test.startTest();
        List<Opportunity> oppList = homeComponentsController.getJobs();
        Test.stopTest();
        System.assertNotEquals(null, oppList);                                                                 
        System.assertEquals(1, oppList.size());        
    }

    @IsTest
    static void testGetApplicants() {
        Test.startTest();
        List<Applicant__c> appList = homeComponentsController.getApplicants();
        Test.stopTest();
        System.assertNotEquals(null, appList);                                                                 
        System.assertEquals(1, appList.size());        
    }
}