force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APL-{000000}-{YYYY}</displayFormat>
        <label>Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appications</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submited to HM</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected by HM</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Situation</fullName>
            </value>
            <value>
                <fullName>Closes</fullName>
            </value>
            <value>
                <fullName>IV Process</fullName>
            </value>
            <value>
                <fullName>Tech Skills</fullName>
            </value>
            <value>
                <fullName>Expectations</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Initial Contact</fullName>
            </value>
            <value>
                <fullName>Motivation</fullName>
            </value>
            <value>
                <fullName>Needs</fullName>
            </value>
            <value>
                <fullName>Relocator</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Candidate USP</fullName>
            </value>
            <value>
                <fullName>Counter Offer</fullName>
            </value>
            <value>
                <fullName>Other Opportunities</fullName>
            </value>
            <value>
                <fullName>Business not to approach</fullName>
            </value>
            <value>
                <fullName>Closing on availability</fullName>
            </value>
            <value>
                <fullName>Selling your service</fullName>
            </value>
            <value>
                <fullName>Selling Exclusivity</fullName>
            </value>
            <value>
                <fullName>Identifying Alarmbells</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ambasador</fullName>
            </value>
            <value>
                <fullName>Top 30</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Market Potential Cands</fullName>
            </value>
            <value>
                <fullName>Incomplete CV</fullName>
            </value>
            <value>
                <fullName>Nog uitzoeken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Client Contact record type</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <description>Freelancer Record type</description>
    <label>Freelance Candidate</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>korter dan 2 weken</fullName>
            </value>
            <value>
                <fullName>2 tot 4 weken</fullName>
            </value>
            <value>
                <fullName>6 tot 12 maanden</fullName>
            </value>
            <value>
                <fullName>Meer dan 12 maanden</fullName>
            </value>
            <value>
                <fullName>Korter dan een maand</fullName>
            </value>
            <value>
                <fullName>1-3 maanden</fullName>
            </value>
            <value>
                <fullName>3-6 maanden</fullName>
            </value>
            <value>
                <fullName>Langer dan 6 maanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5 dagen per week</fullName>
            </value>
            <value>
                <fullName>4 dagen per week</fullName>
            </value>
            <value>
                <fullName>3 dagen per week</fullName>
            </value>
            <value>
                <fullName>2 dagen per week</fullName>
            </value>
            <value>
                <fullName>1 dagen per week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Expected_Start__c.field-meta.xml
<CustomField>
    <fullName>Expected_Start__c</fullName>
    <label>Expected Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Geen voorkeur</fullName>
            </value>
            <value>
                <fullName>1 tot 3 years</fullName>
            </value>
            <value>
                <fullName>3 tot 5 years</fullName>
            </value>
            <value>
                <fullName>Meer dan 5 years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Functie__c.field-meta.xml
<CustomField>
    <fullName>Functie__c</fullName>
    <label>Functie</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/GCLID__c.field-meta.xml
<CustomField>
    <fullName>GCLID__c</fullName>
    <label>Google ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Medior</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Radius__c.field-meta.xml
<CustomField>
    <fullName>Radius__c</fullName>
    <label>Radius</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RequestedContact__c.field-meta.xml
<CustomField>
    <fullName>RequestedContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zoekprofiel doorgeven</fullName>
            </value>
            <value>
                <fullName>Uurtarief opvragen</fullName>
            </value>
            <value>
                <fullName>Beschikbaarheid aanvragen</fullName>
            </value>
            <value>
                <fullName>Freelance opdrachten</fullName>
            </value>
            <value>
                <fullName>Vacatures</fullName>
            </value>
            <value>
                <fullName>Freelance en Vacatures</fullName>
            </value>
            <value>
                <fullName>Terugbelverzoek</fullName>
            </value>
            <value>
                <fullName>Vrijblijvende Offerte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>korter dan 2 weken</fullName>
            </value>
            <value>
                <fullName>2 tot 4 weken</fullName>
            </value>
            <value>
                <fullName>1 tot 2 maanden</fullName>
            </value>
            <value>
                <fullName>3 tot 6 maanden</fullName>
            </value>
            <value>
                <fullName>6 tot 12 maanden</fullName>
            </value>
            <value>
                <fullName>Meer dan 12 maanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5 dagen per week</fullName>
            </value>
            <value>
                <fullName>4 dagen per week</fullName>
            </value>
            <value>
                <fullName>3 dagen per week</fullName>
            </value>
            <value>
                <fullName>2 dagen per week</fullName>
            </value>
            <value>
                <fullName>1 dagen per week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Experience</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GCLID__c.field-meta.xml
<CustomField>
    <fullName>GCLID__c</fullName>
    <label>Google ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LegacyOpaID__c.field-meta.xml
<CustomField>
    <fullName>LegacyOpaID__c</fullName>
    <externalId>true</externalId>
    <label>LegacyOpaID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Radius__c.field-meta.xml
<CustomField>
    <fullName>Radius__c</fullName>
    <label>Radius</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Freelance.recordType-meta.xml
<RecordType>
    <fullName>Freelance</fullName>
    <active>true</active>
    <businessProcess>Freelance</businessProcess>
    <label>Freelance</label>
</RecordType>

force-app/main/default/globalValueSets/Experience.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Geen voorkeur</fullName>
    </customValue>
    <customValue>
        <fullName>1 tot 3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3 tot 5 years</fullName>
    </customValue>
    <customValue>
        <fullName>Meer dan 5 years</fullName>
    </customValue>
    <masterLabel>Experience</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Medior</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/webformRegistration.cls
@RestResource(urlMapping='/webform/Register')
global with sharing class webformRegistration {

    @HttpPost
    global static String webformRegister() {
        String result;
        requestWrapper req = new requestWrapper();
        try {
            String request = RestContext.request.requestBody.toString();
            if (String.isBlank(request)) return 'Error: Empty request';
            req = (requestWrapper)JSON.deserialize(request, requestWrapper.class);
            system.debug('Request: '+req);
        } catch(JSONException e) {
            return 'Error: '+e.getMessage();
        }
        switch on req.type {
            when 'client', 'contact' {
                result = validateLead(req);
                if (result!='') return 'Error:' +result;
                result = req.type=='client' ? handleNewLead(req) : handleNewContact(req);
            }
            when 'direct' {
                result = handleNewApplication(req);
            }
            when else {
                result = 'Error: Invalid request type';
            }
        }
        return result;
    }

    private static String handleNewLead(requestWrapper value) {
        Lead newLead = createNewLead(value);
        newLead.Title = value.title;
        newLead.Level__c = value.level;
        newLead.Experience__c = value.experience;
        newLead.Effort__c = value.effort;
        newLead.Duration__c = value.duration;
        if (value.requestType=='Beschikbaarheid aanvragen') {
            if (value.requestContact!=null) {
                newLead.RequestedContact__c = getCandidate(value);
            } 
            else {
                return 'Error: Requested contact is empty';
            }
        }
        try {
            insert newLead;
        } catch (System.Exception e) {
            return 'Error: '+e.getMessage();
        }
        return 'Success';
    }

    private static String handleNewContact(requestWrapper value) {
        // add handle type=Vacatures and no Company => just Contact. What Contact status should be?
        Lead newLead = createNewLead(value);
        newLead.City__c = value.city;
        newLead.Radius__c = value.redius;
        newLead.Work_Location__longitude__s = value.longitude;
        newLead.Work_Location__latitude__s = value.latitude;
        try {
            insert newLead;
        } catch (System.Exception e) {
            return 'Error: '+e.getMessage();
        }
        if (value.fileBase64!=null)
            return handleFileUpload(
                newLead.Id,
                'CV-'+value.firstName+' '+value.lastName,
                'CV-'+value.firstName+' '+value.lastName+'.'+value.fileExtension,
                value.fileBase64
            );
        return 'Success';
    }

    private static Lead createNewLead(requestWrapper value) {
        Lead newLead = new Lead( Status = 'New', LeadSource = 'Website' );
        newLead.firstName = value.firstName;
        newLead.lastName = value.lastName;
        newLead.Email = value.email;
        newLead.Phone = value.phone;
        newLead.City = value.location;
        newLead.Company = value.company;
        newLead.Type__c = value.requestType;
        newLead.Functie__c = value.function;
        newLead.Description = value.description + (value.question!=null ? '\n'+value.question : '');
        newLead.Expected_Start__c = value.startDate;
        newLead.LeadSource = value.source;
        newLead.GCLID__c = value.gclid;
        newLead.utm_source__c = value.utm_source;
        newLead.utm_campaign__c = value.utm_campaign;
        newLead.utm_content__c = value.utm_content;
        newLead.utm_term__c = value.utm_term;
        return newLead;
    }

    private static String validateLead(requestWrapper value) {
        String result = '';
        if (String.isBlank(value.lastName)) result+=' - Last Name cannot be empty - ';
        // we can remove validation if Personal Accounts are on
        if (String.isBlank(value.company) && value.type=='client') {
            result+=' - Company cannot be empty - ';
        } else if (String.isBlank(value.company) && value.type=='contact') {
            value.company = 'Freelance';
        }
        return result;
    }

    private static String handleNewApplication(requestWrapper value) {
        if (String.isNotBlank(value.jobLegacyId) || String.isNotBlank(value.jobId)) {
            Applicant__c newAppl = new Applicant__c();
            if (String.isNotBlank(value.jobLegacyId)) {
                newAppl.Job__c = getJobLegacyID(value.jobLegacyID);
            } else {
                newAppl.Job__c = getJobByID(value.jobId);
            }
            newAppl.Candidate__c = getCandidate(value);
            newAppl.Status__c = 'New';
            if (newAppl.Job__c!=null) {
                try {
                    insert newAppl;
                } catch (Exception e) {
                    return 'Error: '+e.getMessage();
                }
                if (value.fileBase64!=null && value.fileExtension!=null) {
                    return handleFileUpload(
                        newAppl.Candidate__c, 
                        'CV-'+value.firstName+' '+value.lastName, 
                        'CV-'+value.firstName+' '+value.lastName+'.'+value.fileExtension, 
                        value.fileBase64
                    );
                }
            } else {
                return 'Error: Job ID is not found';
            }
        } else {
            return 'Error: Job ID is empty';
        }
        return 'Success';
    }

    private static String getJobByID(String strId) {
        List<Opportunity> appJob = [SELECT Id FROM Opportunity WHERE Id=:strId];
        if (!appJob.isEmpty()) {
            return appJob[0].Id;
        }
        return null;
    }

    private static String getJobLegacyID(String legacyId) {
        List<Opportunity> appJob = [SELECT Id FROM Opportunity WHERE LegacyOpaID__c=:legacyId];
        if (!appJob.isEmpty()) {
            return appJob[0].Id;
        } else {
            Opportunity tmpJob = new Opportunity();
            tmpJob.Name = legacyId;
            tmpJob.StageName = 'New';
            tmpJob.CloseDate = Date.today().addDays(30);
            tmpJob.LegacyOpaID__c = legacyId;
            insert tmpJob;
            return tmpJob.Id;
        }
    }

    private static String getCandidate(requestWrapper value) {
        String searchEmail = value.type=='direct' ? value.email : value.requestContact;
        List<Contact> contList = [SELECT Id FROM Contact WHERE Email=:searchEmail ORDER BY LastModifiedDate DESC];
        if (!contList.isEmpty())
            return contList[0].Id;
        else {
            Contact newContact = new Contact(
                Email = searchEmail
            );
            if (value.type=='direct') {
                newContact.FirstName = value.firstName;
                newContact.LastName = value.lastName;
                newContact.Phone = value.phone;
                newContact.Title = value.function;
                newContact.MailingCity = value.location;
            } else {
                newContact.LastName = 'Not Found';
            }
            insert newContact;
            return newContact.Id;
        }
    }

    private static String handleFileUpload(String Id, String title, String fileName, String base64) {
        try {
            ContentVersion conVer = new ContentVersion();
            conVer.ContentLocation = 'S';
            conVer.PathOnClient = fileName;
            conVer.Title = title;
            conVer.VersionData = EncodingUtil.base64Decode(base64);
            insert conVer;

            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
            
            ContentDocumentLink cDe = new ContentDocumentLink();
            cDe.ContentDocumentId = conDoc;
            cDe.LinkedEntityId = Id;
            cDe.ShareType = 'I';
            //cDe.Visibility = 'InternalUsers';
            insert cDe;
        } catch (Exception e) {
            return 'Error: '+e.getMessage();
        }
        return 'Success';
    }

    class requestWrapper {
        String function;
        String description;
        String effort;
        String duration;
        String startDate;
        String location;
        String question;
        String level;
        String experience;
        String requestType;
        String requestContact;

        String gclid;
        String utm_source;
        String utm_campaign;
        String utm_content;
        String utm_term;

        String city; 
        Integer redius;
        Decimal latitude;
        Decimal longitude;
        String fileBase64;
        String fileExtension;
        String jobLegacyId;
        String jobId;

        String company;
        String firstName;
        String lastName;
        String title;
        String phone;
        String email;

        String type;
        String source = 'Capwell';
    }
}